// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "dashboard_user/dashboard_user.proto" (package "dashboard_user", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { DashboardUserService } from "./dashboard_user";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { GetDashboardUserResponse } from "./dashboard_user";
import type { GetDashboardUserRequest } from "./dashboard_user";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service dashboard_user.DashboardUserService
 */
export interface IDashboardUserServiceClient {
    /**
     * @generated from protobuf rpc: GetDashboardUser
     */
    getDashboardUser(input: GetDashboardUserRequest, options?: RpcOptions): UnaryCall<GetDashboardUserRequest, GetDashboardUserResponse>;
}
/**
 * @generated from protobuf service dashboard_user.DashboardUserService
 */
export class DashboardUserServiceClient implements IDashboardUserServiceClient, ServiceInfo {
    typeName = DashboardUserService.typeName;
    methods = DashboardUserService.methods;
    options = DashboardUserService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: GetDashboardUser
     */
    getDashboardUser(input: GetDashboardUserRequest, options?: RpcOptions): UnaryCall<GetDashboardUserRequest, GetDashboardUserResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetDashboardUserRequest, GetDashboardUserResponse>("unary", this._transport, method, opt, input);
    }
}
