// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "auth/auth.proto" (package "auth", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { AuthService } from "./auth";
import type { GetProfileUserResponse } from "./auth";
import type { GetProfileUserRequest } from "./auth";
import type { ChangePasswordPublicResponse } from "./auth";
import type { ChangePasswordPublicRequest } from "./auth";
import type { ForgotPasswordResponse } from "./auth";
import type { ForgotPasswordRequest } from "./auth";
import type { RequestVerifyResponse } from "./auth";
import type { RequestVerifyRequest } from "./auth";
import type { VerifyEmailResponse } from "./auth";
import type { VerifyEmailRequest } from "./auth";
import type { RequestOTPResponse } from "./auth";
import type { RequestOTPRequest } from "./auth";
import type { VerifyResponse } from "./auth";
import type { VerifyRequest } from "./auth";
import type { GetProfileResponse } from "./auth";
import type { GetProfileRequest } from "./auth";
import type { ChangePasswordResponse } from "./auth";
import type { ChangePasswordRequest } from "./auth";
import type { LogoutResponse } from "./auth";
import type { LogoutRequest } from "./auth";
import type { LoginWithGoogleResponse } from "./auth";
import type { LoginWithGoogleRequest } from "./auth";
import type { LoginResponse } from "./auth";
import type { LoginRequest } from "./auth";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { RegisterResponse } from "./auth";
import type { RegisterRequest } from "./auth";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service auth.AuthService
 */
export interface IAuthServiceClient {
    /**
     * @generated from protobuf rpc: Register
     */
    register(input: RegisterRequest, options?: RpcOptions): UnaryCall<RegisterRequest, RegisterResponse>;
    /**
     * @generated from protobuf rpc: Login
     */
    login(input: LoginRequest, options?: RpcOptions): UnaryCall<LoginRequest, LoginResponse>;
    /**
     * @generated from protobuf rpc: LoginWithGoogle
     */
    loginWithGoogle(input: LoginWithGoogleRequest, options?: RpcOptions): UnaryCall<LoginWithGoogleRequest, LoginWithGoogleResponse>;
    /**
     * @generated from protobuf rpc: Logout
     */
    logout(input: LogoutRequest, options?: RpcOptions): UnaryCall<LogoutRequest, LogoutResponse>;
    /**
     * @generated from protobuf rpc: ChangePassword
     */
    changePassword(input: ChangePasswordRequest, options?: RpcOptions): UnaryCall<ChangePasswordRequest, ChangePasswordResponse>;
    /**
     * @generated from protobuf rpc: GetProfile
     */
    getProfile(input: GetProfileRequest, options?: RpcOptions): UnaryCall<GetProfileRequest, GetProfileResponse>;
    /**
     * @generated from protobuf rpc: Verify
     */
    verify(input: VerifyRequest, options?: RpcOptions): UnaryCall<VerifyRequest, VerifyResponse>;
    /**
     * @generated from protobuf rpc: RequestOTP
     */
    requestOTP(input: RequestOTPRequest, options?: RpcOptions): UnaryCall<RequestOTPRequest, RequestOTPResponse>;
    /**
     * Email link (web)
     *
     * @generated from protobuf rpc: VerifyEmail
     */
    verifyEmail(input: VerifyEmailRequest, options?: RpcOptions): UnaryCall<VerifyEmailRequest, VerifyEmailResponse>;
    /**
     * @generated from protobuf rpc: RequestVerify
     */
    requestVerify(input: RequestVerifyRequest, options?: RpcOptions): UnaryCall<RequestVerifyRequest, RequestVerifyResponse>;
    /**
     * @generated from protobuf rpc: ForgotPassword
     */
    forgotPassword(input: ForgotPasswordRequest, options?: RpcOptions): UnaryCall<ForgotPasswordRequest, ForgotPasswordResponse>;
    /**
     * @generated from protobuf rpc: ChangePasswordPublic
     */
    changePasswordPublic(input: ChangePasswordPublicRequest, options?: RpcOptions): UnaryCall<ChangePasswordPublicRequest, ChangePasswordPublicResponse>;
    /**
     * user
     *
     * @generated from protobuf rpc: GetProfileUser
     */
    getProfileUser(input: GetProfileUserRequest, options?: RpcOptions): UnaryCall<GetProfileUserRequest, GetProfileUserResponse>;
}
/**
 * @generated from protobuf service auth.AuthService
 */
export class AuthServiceClient implements IAuthServiceClient, ServiceInfo {
    typeName = AuthService.typeName;
    methods = AuthService.methods;
    options = AuthService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: Register
     */
    register(input: RegisterRequest, options?: RpcOptions): UnaryCall<RegisterRequest, RegisterResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<RegisterRequest, RegisterResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: Login
     */
    login(input: LoginRequest, options?: RpcOptions): UnaryCall<LoginRequest, LoginResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<LoginRequest, LoginResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: LoginWithGoogle
     */
    loginWithGoogle(input: LoginWithGoogleRequest, options?: RpcOptions): UnaryCall<LoginWithGoogleRequest, LoginWithGoogleResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<LoginWithGoogleRequest, LoginWithGoogleResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: Logout
     */
    logout(input: LogoutRequest, options?: RpcOptions): UnaryCall<LogoutRequest, LogoutResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<LogoutRequest, LogoutResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ChangePassword
     */
    changePassword(input: ChangePasswordRequest, options?: RpcOptions): UnaryCall<ChangePasswordRequest, ChangePasswordResponse> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<ChangePasswordRequest, ChangePasswordResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetProfile
     */
    getProfile(input: GetProfileRequest, options?: RpcOptions): UnaryCall<GetProfileRequest, GetProfileResponse> {
        const method = this.methods[5], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetProfileRequest, GetProfileResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: Verify
     */
    verify(input: VerifyRequest, options?: RpcOptions): UnaryCall<VerifyRequest, VerifyResponse> {
        const method = this.methods[6], opt = this._transport.mergeOptions(options);
        return stackIntercept<VerifyRequest, VerifyResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: RequestOTP
     */
    requestOTP(input: RequestOTPRequest, options?: RpcOptions): UnaryCall<RequestOTPRequest, RequestOTPResponse> {
        const method = this.methods[7], opt = this._transport.mergeOptions(options);
        return stackIntercept<RequestOTPRequest, RequestOTPResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Email link (web)
     *
     * @generated from protobuf rpc: VerifyEmail
     */
    verifyEmail(input: VerifyEmailRequest, options?: RpcOptions): UnaryCall<VerifyEmailRequest, VerifyEmailResponse> {
        const method = this.methods[8], opt = this._transport.mergeOptions(options);
        return stackIntercept<VerifyEmailRequest, VerifyEmailResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: RequestVerify
     */
    requestVerify(input: RequestVerifyRequest, options?: RpcOptions): UnaryCall<RequestVerifyRequest, RequestVerifyResponse> {
        const method = this.methods[9], opt = this._transport.mergeOptions(options);
        return stackIntercept<RequestVerifyRequest, RequestVerifyResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ForgotPassword
     */
    forgotPassword(input: ForgotPasswordRequest, options?: RpcOptions): UnaryCall<ForgotPasswordRequest, ForgotPasswordResponse> {
        const method = this.methods[10], opt = this._transport.mergeOptions(options);
        return stackIntercept<ForgotPasswordRequest, ForgotPasswordResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ChangePasswordPublic
     */
    changePasswordPublic(input: ChangePasswordPublicRequest, options?: RpcOptions): UnaryCall<ChangePasswordPublicRequest, ChangePasswordPublicResponse> {
        const method = this.methods[11], opt = this._transport.mergeOptions(options);
        return stackIntercept<ChangePasswordPublicRequest, ChangePasswordPublicResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * user
     *
     * @generated from protobuf rpc: GetProfileUser
     */
    getProfileUser(input: GetProfileUserRequest, options?: RpcOptions): UnaryCall<GetProfileUserRequest, GetProfileUserResponse> {
        const method = this.methods[12], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetProfileUserRequest, GetProfileUserResponse>("unary", this._transport, method, opt, input);
    }
}
