// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "course/course.proto" (package "course", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { CourseService } from "./course";
import type { HighlightCoursesResponse } from "./course";
import type { HighlightCoursesRequest } from "./course";
import type { DetailCourseGuestResponse } from "./course";
import type { DetailCourseGuestRequest } from "./course";
import type { ListCourseResponse } from "./course";
import type { ListCourseRequest } from "./course";
import type { ListCourseAdminResponse } from "./course";
import type { ListCourseAdminRequest } from "./course";
import type { DetailCourseUserResponse } from "./course";
import type { DetailCourseUserRequest } from "./course";
import type { GetAllCourseUserResponse } from "./course";
import type { GetAllCourseUserRequest } from "./course";
import type { DeleteCourseResponse } from "./course";
import type { DeleteCourseRequest } from "./course";
import type { EditCourseResponse } from "./course";
import type { EditCourseRequest } from "./course";
import type { DetailCourseResponse } from "./course";
import type { DetailCourseRequest } from "./course";
import type { CreateCourseResponse } from "./course";
import type { CreateCourseRequest } from "./course";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { GetAllCourseResponse } from "./course";
import type { GetAllCourseRequest } from "./course";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service course.CourseService
 */
export interface ICourseServiceClient {
    /**
     * @generated from protobuf rpc: GetAllCourse
     */
    getAllCourse(input: GetAllCourseRequest, options?: RpcOptions): UnaryCall<GetAllCourseRequest, GetAllCourseResponse>;
    /**
     * @generated from protobuf rpc: CreateCourse
     */
    createCourse(input: CreateCourseRequest, options?: RpcOptions): UnaryCall<CreateCourseRequest, CreateCourseResponse>;
    /**
     * @generated from protobuf rpc: DetailCourse
     */
    detailCourse(input: DetailCourseRequest, options?: RpcOptions): UnaryCall<DetailCourseRequest, DetailCourseResponse>;
    /**
     * @generated from protobuf rpc: EditCourse
     */
    editCourse(input: EditCourseRequest, options?: RpcOptions): UnaryCall<EditCourseRequest, EditCourseResponse>;
    /**
     * @generated from protobuf rpc: DeleteCourse
     */
    deleteCourse(input: DeleteCourseRequest, options?: RpcOptions): UnaryCall<DeleteCourseRequest, DeleteCourseResponse>;
    /**
     * USER
     *
     * @generated from protobuf rpc: GetAllCourseUser
     */
    getAllCourseUser(input: GetAllCourseUserRequest, options?: RpcOptions): UnaryCall<GetAllCourseUserRequest, GetAllCourseUserResponse>;
    /**
     * @generated from protobuf rpc: DetailCourseUser
     */
    detailCourseUser(input: DetailCourseUserRequest, options?: RpcOptions): UnaryCall<DetailCourseUserRequest, DetailCourseUserResponse>;
    /**
     * @generated from protobuf rpc: ListCourseAdmin
     */
    listCourseAdmin(input: ListCourseAdminRequest, options?: RpcOptions): UnaryCall<ListCourseAdminRequest, ListCourseAdminResponse>;
    /**
     * guest
     *
     * @generated from protobuf rpc: ListCourse
     */
    listCourse(input: ListCourseRequest, options?: RpcOptions): UnaryCall<ListCourseRequest, ListCourseResponse>;
    /**
     * @generated from protobuf rpc: DetailCourseGuest
     */
    detailCourseGuest(input: DetailCourseGuestRequest, options?: RpcOptions): UnaryCall<DetailCourseGuestRequest, DetailCourseGuestResponse>;
    /**
     * @generated from protobuf rpc: HighlightCourses
     */
    highlightCourses(input: HighlightCoursesRequest, options?: RpcOptions): UnaryCall<HighlightCoursesRequest, HighlightCoursesResponse>;
}
/**
 * @generated from protobuf service course.CourseService
 */
export class CourseServiceClient implements ICourseServiceClient, ServiceInfo {
    typeName = CourseService.typeName;
    methods = CourseService.methods;
    options = CourseService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: GetAllCourse
     */
    getAllCourse(input: GetAllCourseRequest, options?: RpcOptions): UnaryCall<GetAllCourseRequest, GetAllCourseResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetAllCourseRequest, GetAllCourseResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: CreateCourse
     */
    createCourse(input: CreateCourseRequest, options?: RpcOptions): UnaryCall<CreateCourseRequest, CreateCourseResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<CreateCourseRequest, CreateCourseResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DetailCourse
     */
    detailCourse(input: DetailCourseRequest, options?: RpcOptions): UnaryCall<DetailCourseRequest, DetailCourseResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<DetailCourseRequest, DetailCourseResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: EditCourse
     */
    editCourse(input: EditCourseRequest, options?: RpcOptions): UnaryCall<EditCourseRequest, EditCourseResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<EditCourseRequest, EditCourseResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DeleteCourse
     */
    deleteCourse(input: DeleteCourseRequest, options?: RpcOptions): UnaryCall<DeleteCourseRequest, DeleteCourseResponse> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeleteCourseRequest, DeleteCourseResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * USER
     *
     * @generated from protobuf rpc: GetAllCourseUser
     */
    getAllCourseUser(input: GetAllCourseUserRequest, options?: RpcOptions): UnaryCall<GetAllCourseUserRequest, GetAllCourseUserResponse> {
        const method = this.methods[5], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetAllCourseUserRequest, GetAllCourseUserResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DetailCourseUser
     */
    detailCourseUser(input: DetailCourseUserRequest, options?: RpcOptions): UnaryCall<DetailCourseUserRequest, DetailCourseUserResponse> {
        const method = this.methods[6], opt = this._transport.mergeOptions(options);
        return stackIntercept<DetailCourseUserRequest, DetailCourseUserResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListCourseAdmin
     */
    listCourseAdmin(input: ListCourseAdminRequest, options?: RpcOptions): UnaryCall<ListCourseAdminRequest, ListCourseAdminResponse> {
        const method = this.methods[7], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListCourseAdminRequest, ListCourseAdminResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * guest
     *
     * @generated from protobuf rpc: ListCourse
     */
    listCourse(input: ListCourseRequest, options?: RpcOptions): UnaryCall<ListCourseRequest, ListCourseResponse> {
        const method = this.methods[8], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListCourseRequest, ListCourseResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DetailCourseGuest
     */
    detailCourseGuest(input: DetailCourseGuestRequest, options?: RpcOptions): UnaryCall<DetailCourseGuestRequest, DetailCourseGuestResponse> {
        const method = this.methods[9], opt = this._transport.mergeOptions(options);
        return stackIntercept<DetailCourseGuestRequest, DetailCourseGuestResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: HighlightCourses
     */
    highlightCourses(input: HighlightCoursesRequest, options?: RpcOptions): UnaryCall<HighlightCoursesRequest, HighlightCoursesResponse> {
        const method = this.methods[10], opt = this._transport.mergeOptions(options);
        return stackIntercept<HighlightCoursesRequest, HighlightCoursesResponse>("unary", this._transport, method, opt, input);
    }
}
