// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "course/course.proto" (package "course", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { CourseService } from "./course";
import type { DeleteCourseResponse } from "./course";
import type { DeleteCourseRequest } from "./course";
import type { EditCourseResponse } from "./course";
import type { EditCourseRequest } from "./course";
import type { DetailCourseResponse } from "./course";
import type { DetailCourseRequest } from "./course";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { CreateCourseResponse } from "./course";
import type { CreateCourseRequest } from "./course";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service course.CourseService
 */
export interface ICourseServiceClient {
    /**
     * @generated from protobuf rpc: CreateCourse
     */
    createCourse(input: CreateCourseRequest, options?: RpcOptions): UnaryCall<CreateCourseRequest, CreateCourseResponse>;
    /**
     * @generated from protobuf rpc: DetailCourse
     */
    detailCourse(input: DetailCourseRequest, options?: RpcOptions): UnaryCall<DetailCourseRequest, DetailCourseResponse>;
    /**
     * @generated from protobuf rpc: EditCourse
     */
    editCourse(input: EditCourseRequest, options?: RpcOptions): UnaryCall<EditCourseRequest, EditCourseResponse>;
    /**
     * @generated from protobuf rpc: DeleteCourse
     */
    deleteCourse(input: DeleteCourseRequest, options?: RpcOptions): UnaryCall<DeleteCourseRequest, DeleteCourseResponse>;
}
/**
 * @generated from protobuf service course.CourseService
 */
export class CourseServiceClient implements ICourseServiceClient, ServiceInfo {
    typeName = CourseService.typeName;
    methods = CourseService.methods;
    options = CourseService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: CreateCourse
     */
    createCourse(input: CreateCourseRequest, options?: RpcOptions): UnaryCall<CreateCourseRequest, CreateCourseResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<CreateCourseRequest, CreateCourseResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DetailCourse
     */
    detailCourse(input: DetailCourseRequest, options?: RpcOptions): UnaryCall<DetailCourseRequest, DetailCourseResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<DetailCourseRequest, DetailCourseResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: EditCourse
     */
    editCourse(input: EditCourseRequest, options?: RpcOptions): UnaryCall<EditCourseRequest, EditCourseResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<EditCourseRequest, EditCourseResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DeleteCourse
     */
    deleteCourse(input: DeleteCourseRequest, options?: RpcOptions): UnaryCall<DeleteCourseRequest, DeleteCourseResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeleteCourseRequest, DeleteCourseResponse>("unary", this._transport, method, opt, input);
    }
}
