// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "enrollment/enrollment.proto" (package "enrollment", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { BaseResponse } from "../common/base_response";
import { FieldMask } from "../google/protobuf/field_mask";
/**
 * @generated from protobuf message enrollment.DetailEnrollByUserRoleRequest
 */
export interface DetailEnrollByUserRoleRequest {
    /**
     * @generated from protobuf field: string course_id = 1
     */
    courseId: string;
    /**
     * @generated from protobuf field: google.protobuf.FieldMask field_mask = 2
     */
    fieldMask?: FieldMask;
}
/**
 * @generated from protobuf message enrollment.DetailEnrollByUserRoleResponse
 */
export interface DetailEnrollByUserRoleResponse {
    /**
     * @generated from protobuf field: common.BaseResponse base = 1
     */
    base?: BaseResponse;
    /**
     * @generated from protobuf field: string id = 14
     */
    id: string;
    /**
     * @generated from protobuf field: optional string user_id = 2
     */
    userId?: string;
    /**
     * @generated from protobuf field: optional string course_id = 3
     */
    courseId?: string;
    /**
     * @generated from protobuf field: optional string instructor_id = 4
     */
    instructorId?: string;
    /**
     * @generated from protobuf field: optional int32 have_access = 5
     */
    haveAccess?: number;
    /**
     * @generated from protobuf field: optional string created_at = 6
     */
    createdAt?: string;
    /**
     * @generated from protobuf field: optional string created_by = 7
     */
    createdBy?: string;
    /**
     * @generated from protobuf field: optional string deleted_by = 8
     */
    deletedBy?: string;
    /**
     * @generated from protobuf field: optional string updated_at = 9
     */
    updatedAt?: string;
    /**
     * @generated from protobuf field: optional string updated_by = 10
     */
    updatedBy?: string;
    /**
     * @generated from protobuf field: optional string deleted_at = 11
     */
    deletedAt?: string;
    /**
     * @generated from protobuf field: optional string user_full_name = 12
     */
    userFullName?: string;
    /**
     * @generated from protobuf field: optional string user_email = 13
     */
    userEmail?: string;
}
// @generated message type with reflection information, may provide speed optimized methods
class DetailEnrollByUserRoleRequest$Type extends MessageType<DetailEnrollByUserRoleRequest> {
    constructor() {
        super("enrollment.DetailEnrollByUserRoleRequest", [
            { no: 1, name: "course_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "field_mask", kind: "message", T: () => FieldMask }
        ]);
    }
    create(value?: PartialMessage<DetailEnrollByUserRoleRequest>): DetailEnrollByUserRoleRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.courseId = "";
        if (value !== undefined)
            reflectionMergePartial<DetailEnrollByUserRoleRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DetailEnrollByUserRoleRequest): DetailEnrollByUserRoleRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string course_id */ 1:
                    message.courseId = reader.string();
                    break;
                case /* google.protobuf.FieldMask field_mask */ 2:
                    message.fieldMask = FieldMask.internalBinaryRead(reader, reader.uint32(), options, message.fieldMask);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: DetailEnrollByUserRoleRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string course_id = 1; */
        if (message.courseId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.courseId);
        /* google.protobuf.FieldMask field_mask = 2; */
        if (message.fieldMask)
            FieldMask.internalBinaryWrite(message.fieldMask, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message enrollment.DetailEnrollByUserRoleRequest
 */
export const DetailEnrollByUserRoleRequest = new DetailEnrollByUserRoleRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DetailEnrollByUserRoleResponse$Type extends MessageType<DetailEnrollByUserRoleResponse> {
    constructor() {
        super("enrollment.DetailEnrollByUserRoleResponse", [
            { no: 1, name: "base", kind: "message", T: () => BaseResponse },
            { no: 14, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "user_id", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "course_id", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "instructor_id", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "have_access", kind: "scalar", opt: true, T: 5 /*ScalarType.INT32*/ },
            { no: 6, name: "created_at", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 7, name: "created_by", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 8, name: "deleted_by", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 9, name: "updated_at", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 10, name: "updated_by", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 11, name: "deleted_at", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 12, name: "user_full_name", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 13, name: "user_email", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<DetailEnrollByUserRoleResponse>): DetailEnrollByUserRoleResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        if (value !== undefined)
            reflectionMergePartial<DetailEnrollByUserRoleResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DetailEnrollByUserRoleResponse): DetailEnrollByUserRoleResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* common.BaseResponse base */ 1:
                    message.base = BaseResponse.internalBinaryRead(reader, reader.uint32(), options, message.base);
                    break;
                case /* string id */ 14:
                    message.id = reader.string();
                    break;
                case /* optional string user_id */ 2:
                    message.userId = reader.string();
                    break;
                case /* optional string course_id */ 3:
                    message.courseId = reader.string();
                    break;
                case /* optional string instructor_id */ 4:
                    message.instructorId = reader.string();
                    break;
                case /* optional int32 have_access */ 5:
                    message.haveAccess = reader.int32();
                    break;
                case /* optional string created_at */ 6:
                    message.createdAt = reader.string();
                    break;
                case /* optional string created_by */ 7:
                    message.createdBy = reader.string();
                    break;
                case /* optional string deleted_by */ 8:
                    message.deletedBy = reader.string();
                    break;
                case /* optional string updated_at */ 9:
                    message.updatedAt = reader.string();
                    break;
                case /* optional string updated_by */ 10:
                    message.updatedBy = reader.string();
                    break;
                case /* optional string deleted_at */ 11:
                    message.deletedAt = reader.string();
                    break;
                case /* optional string user_full_name */ 12:
                    message.userFullName = reader.string();
                    break;
                case /* optional string user_email */ 13:
                    message.userEmail = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: DetailEnrollByUserRoleResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* common.BaseResponse base = 1; */
        if (message.base)
            BaseResponse.internalBinaryWrite(message.base, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* optional string user_id = 2; */
        if (message.userId !== undefined)
            writer.tag(2, WireType.LengthDelimited).string(message.userId);
        /* optional string course_id = 3; */
        if (message.courseId !== undefined)
            writer.tag(3, WireType.LengthDelimited).string(message.courseId);
        /* optional string instructor_id = 4; */
        if (message.instructorId !== undefined)
            writer.tag(4, WireType.LengthDelimited).string(message.instructorId);
        /* optional int32 have_access = 5; */
        if (message.haveAccess !== undefined)
            writer.tag(5, WireType.Varint).int32(message.haveAccess);
        /* optional string created_at = 6; */
        if (message.createdAt !== undefined)
            writer.tag(6, WireType.LengthDelimited).string(message.createdAt);
        /* optional string created_by = 7; */
        if (message.createdBy !== undefined)
            writer.tag(7, WireType.LengthDelimited).string(message.createdBy);
        /* optional string deleted_by = 8; */
        if (message.deletedBy !== undefined)
            writer.tag(8, WireType.LengthDelimited).string(message.deletedBy);
        /* optional string updated_at = 9; */
        if (message.updatedAt !== undefined)
            writer.tag(9, WireType.LengthDelimited).string(message.updatedAt);
        /* optional string updated_by = 10; */
        if (message.updatedBy !== undefined)
            writer.tag(10, WireType.LengthDelimited).string(message.updatedBy);
        /* optional string deleted_at = 11; */
        if (message.deletedAt !== undefined)
            writer.tag(11, WireType.LengthDelimited).string(message.deletedAt);
        /* optional string user_full_name = 12; */
        if (message.userFullName !== undefined)
            writer.tag(12, WireType.LengthDelimited).string(message.userFullName);
        /* optional string user_email = 13; */
        if (message.userEmail !== undefined)
            writer.tag(13, WireType.LengthDelimited).string(message.userEmail);
        /* string id = 14; */
        if (message.id !== "")
            writer.tag(14, WireType.LengthDelimited).string(message.id);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message enrollment.DetailEnrollByUserRoleResponse
 */
export const DetailEnrollByUserRoleResponse = new DetailEnrollByUserRoleResponse$Type();
/**
 * @generated ServiceType for protobuf service enrollment.EnrollmentService
 */
export const EnrollmentService = new ServiceType("enrollment.EnrollmentService", [
    { name: "DetailEnrollByUserRole", options: {}, I: DetailEnrollByUserRoleRequest, O: DetailEnrollByUserRoleResponse }
]);
