// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "enrollment/enrollment.proto" (package "enrollment", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { EnrollmentService } from "./enrollment";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { DetailEnrollByUserRoleResponse } from "./enrollment";
import type { DetailEnrollByUserRoleRequest } from "./enrollment";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service enrollment.EnrollmentService
 */
export interface IEnrollmentServiceClient {
    /**
     * rpc CreateCourse (CreateCourseRequest) returns (CreateCourseResponse);
     * rpc DetailCourse (DetailCourseRequest) returns (DetailCourseResponse);
     * rpc EditCourse (EditCourseRequest) returns (EditCourseResponse);
     * rpc DeleteCourse (DeleteCourseRequest) returns (DeleteCourseResponse);
     * // USER
     * rpc GetAllCourseUser (GetAllCourseUserRequest) returns (GetAllCourseUserResponse);
     * rpc DetailCourseUser (DetailCourseUserRequest) returns (DetailCourseUserResponse);
     *
     * @generated from protobuf rpc: DetailEnrollByUserRole
     */
    detailEnrollByUserRole(input: DetailEnrollByUserRoleRequest, options?: RpcOptions): UnaryCall<DetailEnrollByUserRoleRequest, DetailEnrollByUserRoleResponse>;
}
/**
 * @generated from protobuf service enrollment.EnrollmentService
 */
export class EnrollmentServiceClient implements IEnrollmentServiceClient, ServiceInfo {
    typeName = EnrollmentService.typeName;
    methods = EnrollmentService.methods;
    options = EnrollmentService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * rpc CreateCourse (CreateCourseRequest) returns (CreateCourseResponse);
     * rpc DetailCourse (DetailCourseRequest) returns (DetailCourseResponse);
     * rpc EditCourse (EditCourseRequest) returns (EditCourseResponse);
     * rpc DeleteCourse (DeleteCourseRequest) returns (DeleteCourseResponse);
     * // USER
     * rpc GetAllCourseUser (GetAllCourseUserRequest) returns (GetAllCourseUserResponse);
     * rpc DetailCourseUser (DetailCourseUserRequest) returns (DetailCourseUserResponse);
     *
     * @generated from protobuf rpc: DetailEnrollByUserRole
     */
    detailEnrollByUserRole(input: DetailEnrollByUserRoleRequest, options?: RpcOptions): UnaryCall<DetailEnrollByUserRoleRequest, DetailEnrollByUserRoleResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<DetailEnrollByUserRoleRequest, DetailEnrollByUserRoleResponse>("unary", this._transport, method, opt, input);
    }
}
