// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "cart/cart.proto" (package "cart", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { CartService } from "./cart";
import type { CartCountResponse } from "./cart";
import type { CartCountRequest } from "./cart";
import type { UpdateCartQuantityResponse } from "./cart";
import type { UpdateCartQuantityRequest } from "./cart";
import type { DeleteCartResponse } from "./cart";
import type { DeleteCartRequest } from "./cart";
import type { ListCartResponse } from "./cart";
import type { ListCartRequest } from "./cart";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { AddCourseToCartResponse } from "./cart";
import type { AddCourseToCartRequest } from "./cart";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service cart.CartService
 */
export interface ICartServiceClient {
    /**
     * @generated from protobuf rpc: AddCourseToCart
     */
    addCourseToCart(input: AddCourseToCartRequest, options?: RpcOptions): UnaryCall<AddCourseToCartRequest, AddCourseToCartResponse>;
    /**
     * @generated from protobuf rpc: ListCart
     */
    listCart(input: ListCartRequest, options?: RpcOptions): UnaryCall<ListCartRequest, ListCartResponse>;
    /**
     * @generated from protobuf rpc: DeleteCart
     */
    deleteCart(input: DeleteCartRequest, options?: RpcOptions): UnaryCall<DeleteCartRequest, DeleteCartResponse>;
    /**
     * @generated from protobuf rpc: UpdateCartQuantity
     */
    updateCartQuantity(input: UpdateCartQuantityRequest, options?: RpcOptions): UnaryCall<UpdateCartQuantityRequest, UpdateCartQuantityResponse>;
    /**
     * @generated from protobuf rpc: CartCount
     */
    cartCount(input: CartCountRequest, options?: RpcOptions): UnaryCall<CartCountRequest, CartCountResponse>;
}
/**
 * @generated from protobuf service cart.CartService
 */
export class CartServiceClient implements ICartServiceClient, ServiceInfo {
    typeName = CartService.typeName;
    methods = CartService.methods;
    options = CartService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: AddCourseToCart
     */
    addCourseToCart(input: AddCourseToCartRequest, options?: RpcOptions): UnaryCall<AddCourseToCartRequest, AddCourseToCartResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<AddCourseToCartRequest, AddCourseToCartResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListCart
     */
    listCart(input: ListCartRequest, options?: RpcOptions): UnaryCall<ListCartRequest, ListCartResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListCartRequest, ListCartResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DeleteCart
     */
    deleteCart(input: DeleteCartRequest, options?: RpcOptions): UnaryCall<DeleteCartRequest, DeleteCartResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeleteCartRequest, DeleteCartResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdateCartQuantity
     */
    updateCartQuantity(input: UpdateCartQuantityRequest, options?: RpcOptions): UnaryCall<UpdateCartQuantityRequest, UpdateCartQuantityResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<UpdateCartQuantityRequest, UpdateCartQuantityResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: CartCount
     */
    cartCount(input: CartCountRequest, options?: RpcOptions): UnaryCall<CartCountRequest, CartCountResponse> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<CartCountRequest, CartCountResponse>("unary", this._transport, method, opt, input);
    }
}
