// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "course_chapter/course_chapter.proto" (package "course_chapter", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { FieldMask } from "../google/protobuf/field_mask";
import { BaseResponse } from "../common/base_response";
/**
 * @generated from protobuf message course_chapter.CreateCourseChapterRequest
 */
export interface CreateCourseChapterRequest {
    /**
     * @generated from protobuf field: string instructor_id = 1
     */
    instructorId: string;
    /**
     * @generated from protobuf field: string course_id = 2
     */
    courseId: string;
    /**
     * @generated from protobuf field: string title = 3
     */
    title: string;
    /**
     * @generated from protobuf field: int`32` order_chapter = 4
     */
    orderChapter: number;
    /**
     * @generated from protobuf field: string status = 5
     */
    status: string;
}
/**
 * @generated from protobuf message course_chapter.CreateCourseChapterResponse
 */
export interface CreateCourseChapterResponse {
    /**
     * @generated from protobuf field: common.BaseResponse base = 1
     */
    base?: BaseResponse;
    /**
     * @generated from protobuf field: string id = 2
     */
    id: string;
}
/**
 * @generated from protobuf message course_chapter.DetailCourseChapterRequest
 */
export interface DetailCourseChapterRequest {
    /**
     * @generated from protobuf field: string id = 1
     */
    id: string;
    /**
     * @generated from protobuf field: google.protobuf.FieldMask field_mask = 2
     */
    fieldMask?: FieldMask;
}
/**
 * @generated from protobuf message course_chapter.DetailCourseChapterResponse
 */
export interface DetailCourseChapterResponse {
    /**
     * @generated from protobuf field: common.BaseResponse base = 1
     */
    base?: BaseResponse;
    /**
     * @generated from protobuf field: string id = 2
     */
    id: string;
    /**
     * @generated from protobuf field: optional string instructor_id = 3
     */
    instructorId?: string;
    /**
     * @generated from protobuf field: optional string course_id = 4
     */
    courseId?: string;
    /**
     * @generated from protobuf field: optional string title = 5
     */
    title?: string;
    /**
     * @generated from protobuf field: optional int32 order_chapter = 6
     */
    orderChapter?: number;
    /**
     * @generated from protobuf field: optional string status = 7
     */
    status?: string;
    /**
     * @generated from protobuf field: optional string created_at = 8
     */
    createdAt?: string;
    /**
     * @generated from protobuf field: optional string created_by = 9
     */
    createdBy?: string;
    /**
     * @generated from protobuf field: optional string deleted_by = 10
     */
    deletedBy?: string;
    /**
     * @generated from protobuf field: optional string updated_at = 11
     */
    updatedAt?: string;
    /**
     * @generated from protobuf field: optional string updated_by = 12
     */
    updatedBy?: string;
    /**
     * @generated from protobuf field: optional string deleted_at = 13
     */
    deletedAt?: string;
}
/**
 * @generated from protobuf message course_chapter.EditCourseChapterRequest
 */
export interface EditCourseChapterRequest {
    /**
     * @generated from protobuf field: string id = 1
     */
    id: string;
    /**
     * @generated from protobuf field: string instructor_id = 2
     */
    instructorId: string;
    /**
     * @generated from protobuf field: string course_id = 3
     */
    courseId: string;
    /**
     * @generated from protobuf field: string title = 4
     */
    title: string;
    /**
     * @generated from protobuf field: int32 order_chapter = 5
     */
    orderChapter: number;
    /**
     * @generated from protobuf field: string status = 6
     */
    status: string;
}
/**
 * @generated from protobuf message course_chapter.EditCourseChapterResponse
 */
export interface EditCourseChapterResponse {
    /**
     * @generated from protobuf field: common.BaseResponse base = 1
     */
    base?: BaseResponse;
    /**
     * @generated from protobuf field: string id = 2
     */
    id: string;
}
/**
 * @generated from protobuf message course_chapter.DeleteCourseChapterRequest
 */
export interface DeleteCourseChapterRequest {
    /**
     * @generated from protobuf field: string id = 1
     */
    id: string;
}
/**
 * @generated from protobuf message course_chapter.DeleteCourseChapterResponse
 */
export interface DeleteCourseChapterResponse {
    /**
     * @generated from protobuf field: common.BaseResponse base = 1
     */
    base?: BaseResponse;
}
// @generated message type with reflection information, may provide speed optimized methods
class CreateCourseChapterRequest$Type extends MessageType<CreateCourseChapterRequest> {
    constructor() {
        super("course_chapter.CreateCourseChapterRequest", [
            { no: 1, name: "instructor_id", kind: "scalar", T: 9 /*ScalarType.STRING*/, options: { "buf.validate.field": { string: { minLen: "1", maxLen: "255" } } } },
            { no: 2, name: "course_id", kind: "scalar", T: 9 /*ScalarType.STRING*/, options: { "buf.validate.field": { string: { minLen: "1", maxLen: "255" } } } },
            { no: 3, name: "title", kind: "scalar", T: 9 /*ScalarType.STRING*/, options: { "buf.validate.field": { string: { minLen: "1", maxLen: "255" } } } },
            { no: 4, name: "order_chapter", kind: "scalar", T: 5 /*ScalarType.INT32*/, options: { "buf.validate.field": { int32: { gte: 0 } } } },
            { no: 5, name: "status", kind: "scalar", T: 9 /*ScalarType.STRING*/, options: { "buf.validate.field": { string: { maxLen: "255" } } } }
        ]);
    }
    create(value?: PartialMessage<CreateCourseChapterRequest>): CreateCourseChapterRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.instructorId = "";
        message.courseId = "";
        message.title = "";
        message.orderChapter = 0;
        message.status = "";
        if (value !== undefined)
            reflectionMergePartial<CreateCourseChapterRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CreateCourseChapterRequest): CreateCourseChapterRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string instructor_id */ 1:
                    message.instructorId = reader.string();
                    break;
                case /* string course_id */ 2:
                    message.courseId = reader.string();
                    break;
                case /* string title */ 3:
                    message.title = reader.string();
                    break;
                case /* int32 order_chapter */ 4:
                    message.orderChapter = reader.int32();
                    break;
                case /* string status */ 5:
                    message.status = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CreateCourseChapterRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string instructor_id = 1; */
        if (message.instructorId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.instructorId);
        /* string course_id = 2; */
        if (message.courseId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.courseId);
        /* string title = 3; */
        if (message.title !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.title);
        /* int32 order_chapter = 4; */
        if (message.orderChapter !== 0)
            writer.tag(4, WireType.Varint).int32(message.orderChapter);
        /* string status = 5; */
        if (message.status !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.status);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message course_chapter.CreateCourseChapterRequest
 */
export const CreateCourseChapterRequest = new CreateCourseChapterRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CreateCourseChapterResponse$Type extends MessageType<CreateCourseChapterResponse> {
    constructor() {
        super("course_chapter.CreateCourseChapterResponse", [
            { no: 1, name: "base", kind: "message", T: () => BaseResponse },
            { no: 2, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<CreateCourseChapterResponse>): CreateCourseChapterResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        if (value !== undefined)
            reflectionMergePartial<CreateCourseChapterResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CreateCourseChapterResponse): CreateCourseChapterResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* common.BaseResponse base */ 1:
                    message.base = BaseResponse.internalBinaryRead(reader, reader.uint32(), options, message.base);
                    break;
                case /* string id */ 2:
                    message.id = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CreateCourseChapterResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* common.BaseResponse base = 1; */
        if (message.base)
            BaseResponse.internalBinaryWrite(message.base, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* string id = 2; */
        if (message.id !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.id);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message course_chapter.CreateCourseChapterResponse
 */
export const CreateCourseChapterResponse = new CreateCourseChapterResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DetailCourseChapterRequest$Type extends MessageType<DetailCourseChapterRequest> {
    constructor() {
        super("course_chapter.DetailCourseChapterRequest", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/, options: { "buf.validate.field": { string: { minLen: "1", maxLen: "255" } } } },
            { no: 2, name: "field_mask", kind: "message", T: () => FieldMask }
        ]);
    }
    create(value?: PartialMessage<DetailCourseChapterRequest>): DetailCourseChapterRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        if (value !== undefined)
            reflectionMergePartial<DetailCourseChapterRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DetailCourseChapterRequest): DetailCourseChapterRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                case /* google.protobuf.FieldMask field_mask */ 2:
                    message.fieldMask = FieldMask.internalBinaryRead(reader, reader.uint32(), options, message.fieldMask);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: DetailCourseChapterRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        /* google.protobuf.FieldMask field_mask = 2; */
        if (message.fieldMask)
            FieldMask.internalBinaryWrite(message.fieldMask, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message course_chapter.DetailCourseChapterRequest
 */
export const DetailCourseChapterRequest = new DetailCourseChapterRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DetailCourseChapterResponse$Type extends MessageType<DetailCourseChapterResponse> {
    constructor() {
        super("course_chapter.DetailCourseChapterResponse", [
            { no: 1, name: "base", kind: "message", T: () => BaseResponse },
            { no: 2, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "instructor_id", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "course_id", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "title", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "order_chapter", kind: "scalar", opt: true, T: 5 /*ScalarType.INT32*/ },
            { no: 7, name: "status", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 8, name: "created_at", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 9, name: "created_by", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 10, name: "deleted_by", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 11, name: "updated_at", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 12, name: "updated_by", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 13, name: "deleted_at", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<DetailCourseChapterResponse>): DetailCourseChapterResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        if (value !== undefined)
            reflectionMergePartial<DetailCourseChapterResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DetailCourseChapterResponse): DetailCourseChapterResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* common.BaseResponse base */ 1:
                    message.base = BaseResponse.internalBinaryRead(reader, reader.uint32(), options, message.base);
                    break;
                case /* string id */ 2:
                    message.id = reader.string();
                    break;
                case /* optional string instructor_id */ 3:
                    message.instructorId = reader.string();
                    break;
                case /* optional string course_id */ 4:
                    message.courseId = reader.string();
                    break;
                case /* optional string title */ 5:
                    message.title = reader.string();
                    break;
                case /* optional int32 order_chapter */ 6:
                    message.orderChapter = reader.int32();
                    break;
                case /* optional string status */ 7:
                    message.status = reader.string();
                    break;
                case /* optional string created_at */ 8:
                    message.createdAt = reader.string();
                    break;
                case /* optional string created_by */ 9:
                    message.createdBy = reader.string();
                    break;
                case /* optional string deleted_by */ 10:
                    message.deletedBy = reader.string();
                    break;
                case /* optional string updated_at */ 11:
                    message.updatedAt = reader.string();
                    break;
                case /* optional string updated_by */ 12:
                    message.updatedBy = reader.string();
                    break;
                case /* optional string deleted_at */ 13:
                    message.deletedAt = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: DetailCourseChapterResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* common.BaseResponse base = 1; */
        if (message.base)
            BaseResponse.internalBinaryWrite(message.base, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* string id = 2; */
        if (message.id !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.id);
        /* optional string instructor_id = 3; */
        if (message.instructorId !== undefined)
            writer.tag(3, WireType.LengthDelimited).string(message.instructorId);
        /* optional string course_id = 4; */
        if (message.courseId !== undefined)
            writer.tag(4, WireType.LengthDelimited).string(message.courseId);
        /* optional string title = 5; */
        if (message.title !== undefined)
            writer.tag(5, WireType.LengthDelimited).string(message.title);
        /* optional int32 order_chapter = 6; */
        if (message.orderChapter !== undefined)
            writer.tag(6, WireType.Varint).int32(message.orderChapter);
        /* optional string status = 7; */
        if (message.status !== undefined)
            writer.tag(7, WireType.LengthDelimited).string(message.status);
        /* optional string created_at = 8; */
        if (message.createdAt !== undefined)
            writer.tag(8, WireType.LengthDelimited).string(message.createdAt);
        /* optional string created_by = 9; */
        if (message.createdBy !== undefined)
            writer.tag(9, WireType.LengthDelimited).string(message.createdBy);
        /* optional string deleted_by = 10; */
        if (message.deletedBy !== undefined)
            writer.tag(10, WireType.LengthDelimited).string(message.deletedBy);
        /* optional string updated_at = 11; */
        if (message.updatedAt !== undefined)
            writer.tag(11, WireType.LengthDelimited).string(message.updatedAt);
        /* optional string updated_by = 12; */
        if (message.updatedBy !== undefined)
            writer.tag(12, WireType.LengthDelimited).string(message.updatedBy);
        /* optional string deleted_at = 13; */
        if (message.deletedAt !== undefined)
            writer.tag(13, WireType.LengthDelimited).string(message.deletedAt);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message course_chapter.DetailCourseChapterResponse
 */
export const DetailCourseChapterResponse = new DetailCourseChapterResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class EditCourseChapterRequest$Type extends MessageType<EditCourseChapterRequest> {
    constructor() {
        super("course_chapter.EditCourseChapterRequest", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/, options: { "buf.validate.field": { string: { minLen: "1", maxLen: "255" } } } },
            { no: 2, name: "instructor_id", kind: "scalar", T: 9 /*ScalarType.STRING*/, options: { "buf.validate.field": { string: { minLen: "1", maxLen: "255" } } } },
            { no: 3, name: "course_id", kind: "scalar", T: 9 /*ScalarType.STRING*/, options: { "buf.validate.field": { string: { minLen: "1", maxLen: "255" } } } },
            { no: 4, name: "title", kind: "scalar", T: 9 /*ScalarType.STRING*/, options: { "buf.validate.field": { string: { minLen: "1", maxLen: "255" } } } },
            { no: 5, name: "order_chapter", kind: "scalar", T: 5 /*ScalarType.INT32*/, options: { "buf.validate.field": { int32: { gte: 0 } } } },
            { no: 6, name: "status", kind: "scalar", T: 9 /*ScalarType.STRING*/, options: { "buf.validate.field": { string: { maxLen: "255" } } } }
        ]);
    }
    create(value?: PartialMessage<EditCourseChapterRequest>): EditCourseChapterRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        message.instructorId = "";
        message.courseId = "";
        message.title = "";
        message.orderChapter = 0;
        message.status = "";
        if (value !== undefined)
            reflectionMergePartial<EditCourseChapterRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: EditCourseChapterRequest): EditCourseChapterRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                case /* string instructor_id */ 2:
                    message.instructorId = reader.string();
                    break;
                case /* string course_id */ 3:
                    message.courseId = reader.string();
                    break;
                case /* string title */ 4:
                    message.title = reader.string();
                    break;
                case /* int32 order_chapter */ 5:
                    message.orderChapter = reader.int32();
                    break;
                case /* string status */ 6:
                    message.status = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: EditCourseChapterRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        /* string instructor_id = 2; */
        if (message.instructorId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.instructorId);
        /* string course_id = 3; */
        if (message.courseId !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.courseId);
        /* string title = 4; */
        if (message.title !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.title);
        /* int32 order_chapter = 5; */
        if (message.orderChapter !== 0)
            writer.tag(5, WireType.Varint).int32(message.orderChapter);
        /* string status = 6; */
        if (message.status !== "")
            writer.tag(6, WireType.LengthDelimited).string(message.status);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message course_chapter.EditCourseChapterRequest
 */
export const EditCourseChapterRequest = new EditCourseChapterRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class EditCourseChapterResponse$Type extends MessageType<EditCourseChapterResponse> {
    constructor() {
        super("course_chapter.EditCourseChapterResponse", [
            { no: 1, name: "base", kind: "message", T: () => BaseResponse },
            { no: 2, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<EditCourseChapterResponse>): EditCourseChapterResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        if (value !== undefined)
            reflectionMergePartial<EditCourseChapterResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: EditCourseChapterResponse): EditCourseChapterResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* common.BaseResponse base */ 1:
                    message.base = BaseResponse.internalBinaryRead(reader, reader.uint32(), options, message.base);
                    break;
                case /* string id */ 2:
                    message.id = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: EditCourseChapterResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* common.BaseResponse base = 1; */
        if (message.base)
            BaseResponse.internalBinaryWrite(message.base, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* string id = 2; */
        if (message.id !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.id);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message course_chapter.EditCourseChapterResponse
 */
export const EditCourseChapterResponse = new EditCourseChapterResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DeleteCourseChapterRequest$Type extends MessageType<DeleteCourseChapterRequest> {
    constructor() {
        super("course_chapter.DeleteCourseChapterRequest", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/, options: { "buf.validate.field": { string: { minLen: "1", maxLen: "255" } } } }
        ]);
    }
    create(value?: PartialMessage<DeleteCourseChapterRequest>): DeleteCourseChapterRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        if (value !== undefined)
            reflectionMergePartial<DeleteCourseChapterRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DeleteCourseChapterRequest): DeleteCourseChapterRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: DeleteCourseChapterRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message course_chapter.DeleteCourseChapterRequest
 */
export const DeleteCourseChapterRequest = new DeleteCourseChapterRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DeleteCourseChapterResponse$Type extends MessageType<DeleteCourseChapterResponse> {
    constructor() {
        super("course_chapter.DeleteCourseChapterResponse", [
            { no: 1, name: "base", kind: "message", T: () => BaseResponse }
        ]);
    }
    create(value?: PartialMessage<DeleteCourseChapterResponse>): DeleteCourseChapterResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<DeleteCourseChapterResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DeleteCourseChapterResponse): DeleteCourseChapterResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* common.BaseResponse base */ 1:
                    message.base = BaseResponse.internalBinaryRead(reader, reader.uint32(), options, message.base);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: DeleteCourseChapterResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* common.BaseResponse base = 1; */
        if (message.base)
            BaseResponse.internalBinaryWrite(message.base, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message course_chapter.DeleteCourseChapterResponse
 */
export const DeleteCourseChapterResponse = new DeleteCourseChapterResponse$Type();
/**
 * @generated ServiceType for protobuf service course_chapter.CourseChapterService
 */
export const CourseChapterService = new ServiceType("course_chapter.CourseChapterService", [
    { name: "CreateCourseChapter", options: {}, I: CreateCourseChapterRequest, O: CreateCourseChapterResponse },
    { name: "DetailCourseChapter", options: {}, I: DetailCourseChapterRequest, O: DetailCourseChapterResponse },
    { name: "EditCourseChapter", options: {}, I: EditCourseChapterRequest, O: EditCourseChapterResponse },
    { name: "DeleteCourseChapter", options: {}, I: DeleteCourseChapterRequest, O: DeleteCourseChapterResponse }
]);
