// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "course_chapter/course_chapter.proto" (package "course_chapter", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { CourseChapterService } from "./course_chapter";
import type { DeleteCourseChapterResponse } from "./course_chapter";
import type { DeleteCourseChapterRequest } from "./course_chapter";
import type { EditCourseChapterResponse } from "./course_chapter";
import type { EditCourseChapterRequest } from "./course_chapter";
import type { DetailCourseChapterResponse } from "./course_chapter";
import type { DetailCourseChapterRequest } from "./course_chapter";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { CreateCourseChapterResponse } from "./course_chapter";
import type { CreateCourseChapterRequest } from "./course_chapter";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service course_chapter.CourseChapterService
 */
export interface ICourseChapterServiceClient {
    /**
     * @generated from protobuf rpc: CreateCourseChapter
     */
    createCourseChapter(input: CreateCourseChapterRequest, options?: RpcOptions): UnaryCall<CreateCourseChapterRequest, CreateCourseChapterResponse>;
    /**
     * @generated from protobuf rpc: DetailCourseChapter
     */
    detailCourseChapter(input: DetailCourseChapterRequest, options?: RpcOptions): UnaryCall<DetailCourseChapterRequest, DetailCourseChapterResponse>;
    /**
     * @generated from protobuf rpc: EditCourseChapter
     */
    editCourseChapter(input: EditCourseChapterRequest, options?: RpcOptions): UnaryCall<EditCourseChapterRequest, EditCourseChapterResponse>;
    /**
     * @generated from protobuf rpc: DeleteCourseChapter
     */
    deleteCourseChapter(input: DeleteCourseChapterRequest, options?: RpcOptions): UnaryCall<DeleteCourseChapterRequest, DeleteCourseChapterResponse>;
}
/**
 * @generated from protobuf service course_chapter.CourseChapterService
 */
export class CourseChapterServiceClient implements ICourseChapterServiceClient, ServiceInfo {
    typeName = CourseChapterService.typeName;
    methods = CourseChapterService.methods;
    options = CourseChapterService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: CreateCourseChapter
     */
    createCourseChapter(input: CreateCourseChapterRequest, options?: RpcOptions): UnaryCall<CreateCourseChapterRequest, CreateCourseChapterResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<CreateCourseChapterRequest, CreateCourseChapterResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DetailCourseChapter
     */
    detailCourseChapter(input: DetailCourseChapterRequest, options?: RpcOptions): UnaryCall<DetailCourseChapterRequest, DetailCourseChapterResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<DetailCourseChapterRequest, DetailCourseChapterResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: EditCourseChapter
     */
    editCourseChapter(input: EditCourseChapterRequest, options?: RpcOptions): UnaryCall<EditCourseChapterRequest, EditCourseChapterResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<EditCourseChapterRequest, EditCourseChapterResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DeleteCourseChapter
     */
    deleteCourseChapter(input: DeleteCourseChapterRequest, options?: RpcOptions): UnaryCall<DeleteCourseChapterRequest, DeleteCourseChapterResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeleteCourseChapterRequest, DeleteCourseChapterResponse>("unary", this._transport, method, opt, input);
    }
}
