// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: chapter_lesson/chapter_lesson.proto

package chapter_lesson

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	common "github.com/abu-umair/be-lms-go/pb/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAllChapterLessonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChapterId     string                 `protobuf:"bytes,1,opt,name=chapter_id,json=chapterId,proto3" json:"chapter_id,omitempty"`
	FieldMask     *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=field_mask,json=fieldMask,proto3" json:"field_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllChapterLessonRequest) Reset() {
	*x = GetAllChapterLessonRequest{}
	mi := &file_chapter_lesson_chapter_lesson_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllChapterLessonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllChapterLessonRequest) ProtoMessage() {}

func (x *GetAllChapterLessonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chapter_lesson_chapter_lesson_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllChapterLessonRequest.ProtoReflect.Descriptor instead.
func (*GetAllChapterLessonRequest) Descriptor() ([]byte, []int) {
	return file_chapter_lesson_chapter_lesson_proto_rawDescGZIP(), []int{0}
}

func (x *GetAllChapterLessonRequest) GetChapterId() string {
	if x != nil {
		return x.ChapterId
	}
	return ""
}

func (x *GetAllChapterLessonRequest) GetFieldMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.FieldMask
	}
	return nil
}

type GetAllChapterLessonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *common.BaseResponse   `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Lessons       []*LessonInfo          `protobuf:"bytes,2,rep,name=lessons,proto3" json:"lessons,omitempty"` // 'repeated' untuk array/slice
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllChapterLessonResponse) Reset() {
	*x = GetAllChapterLessonResponse{}
	mi := &file_chapter_lesson_chapter_lesson_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllChapterLessonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllChapterLessonResponse) ProtoMessage() {}

func (x *GetAllChapterLessonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chapter_lesson_chapter_lesson_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllChapterLessonResponse.ProtoReflect.Descriptor instead.
func (*GetAllChapterLessonResponse) Descriptor() ([]byte, []int) {
	return file_chapter_lesson_chapter_lesson_proto_rawDescGZIP(), []int{1}
}

func (x *GetAllChapterLessonResponse) GetBase() *common.BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *GetAllChapterLessonResponse) GetLessons() []*LessonInfo {
	if x != nil {
		return x.Lessons
	}
	return nil
}

type LessonInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	InstructorId  *string                `protobuf:"bytes,2,opt,name=instructor_id,json=instructorId,proto3,oneof" json:"instructor_id,omitempty"`
	CourseId      *string                `protobuf:"bytes,3,opt,name=course_id,json=courseId,proto3,oneof" json:"course_id,omitempty"`
	ChapterId     *string                `protobuf:"bytes,4,opt,name=chapter_id,json=chapterId,proto3,oneof" json:"chapter_id,omitempty"`
	Title         *string                `protobuf:"bytes,5,opt,name=title,proto3,oneof" json:"title,omitempty"`
	OrderLesson   *int32                 `protobuf:"varint,6,opt,name=order_lesson,json=orderLesson,proto3,oneof" json:"order_lesson,omitempty"`
	Slug          *string                `protobuf:"bytes,7,opt,name=slug,proto3,oneof" json:"slug,omitempty"`
	FilePath      *string                `protobuf:"bytes,8,opt,name=file_path,json=filePath,proto3,oneof" json:"file_path,omitempty"`
	StorageLesson *string                `protobuf:"bytes,9,opt,name=storage_lesson,json=storageLesson,proto3,oneof" json:"storage_lesson,omitempty"`
	LessonType    *string                `protobuf:"bytes,10,opt,name=lesson_type,json=lessonType,proto3,oneof" json:"lesson_type,omitempty"`
	Volume        *string                `protobuf:"bytes,11,opt,name=volume,proto3,oneof" json:"volume,omitempty"`
	Duration      *string                `protobuf:"bytes,12,opt,name=duration,proto3,oneof" json:"duration,omitempty"`
	FileType      *string                `protobuf:"bytes,13,opt,name=file_type,json=fileType,proto3,oneof" json:"file_type,omitempty"`
	Downloadable  *string                `protobuf:"bytes,14,opt,name=downloadable,proto3,oneof" json:"downloadable,omitempty"`
	IsPreview     *int32                 `protobuf:"varint,15,opt,name=is_preview,json=isPreview,proto3,oneof" json:"is_preview,omitempty"`
	Status        *string                `protobuf:"bytes,16,opt,name=status,proto3,oneof" json:"status,omitempty"`
	Description   *string                `protobuf:"bytes,17,opt,name=description,proto3,oneof" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LessonInfo) Reset() {
	*x = LessonInfo{}
	mi := &file_chapter_lesson_chapter_lesson_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LessonInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LessonInfo) ProtoMessage() {}

func (x *LessonInfo) ProtoReflect() protoreflect.Message {
	mi := &file_chapter_lesson_chapter_lesson_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LessonInfo.ProtoReflect.Descriptor instead.
func (*LessonInfo) Descriptor() ([]byte, []int) {
	return file_chapter_lesson_chapter_lesson_proto_rawDescGZIP(), []int{2}
}

func (x *LessonInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LessonInfo) GetInstructorId() string {
	if x != nil && x.InstructorId != nil {
		return *x.InstructorId
	}
	return ""
}

func (x *LessonInfo) GetCourseId() string {
	if x != nil && x.CourseId != nil {
		return *x.CourseId
	}
	return ""
}

func (x *LessonInfo) GetChapterId() string {
	if x != nil && x.ChapterId != nil {
		return *x.ChapterId
	}
	return ""
}

func (x *LessonInfo) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *LessonInfo) GetOrderLesson() int32 {
	if x != nil && x.OrderLesson != nil {
		return *x.OrderLesson
	}
	return 0
}

func (x *LessonInfo) GetSlug() string {
	if x != nil && x.Slug != nil {
		return *x.Slug
	}
	return ""
}

func (x *LessonInfo) GetFilePath() string {
	if x != nil && x.FilePath != nil {
		return *x.FilePath
	}
	return ""
}

func (x *LessonInfo) GetStorageLesson() string {
	if x != nil && x.StorageLesson != nil {
		return *x.StorageLesson
	}
	return ""
}

func (x *LessonInfo) GetLessonType() string {
	if x != nil && x.LessonType != nil {
		return *x.LessonType
	}
	return ""
}

func (x *LessonInfo) GetVolume() string {
	if x != nil && x.Volume != nil {
		return *x.Volume
	}
	return ""
}

func (x *LessonInfo) GetDuration() string {
	if x != nil && x.Duration != nil {
		return *x.Duration
	}
	return ""
}

func (x *LessonInfo) GetFileType() string {
	if x != nil && x.FileType != nil {
		return *x.FileType
	}
	return ""
}

func (x *LessonInfo) GetDownloadable() string {
	if x != nil && x.Downloadable != nil {
		return *x.Downloadable
	}
	return ""
}

func (x *LessonInfo) GetIsPreview() int32 {
	if x != nil && x.IsPreview != nil {
		return *x.IsPreview
	}
	return 0
}

func (x *LessonInfo) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

func (x *LessonInfo) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

type CreateChapterLessonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstructorId  *string                `protobuf:"bytes,1,opt,name=instructor_id,json=instructorId,proto3,oneof" json:"instructor_id,omitempty"`
	CourseId      *string                `protobuf:"bytes,2,opt,name=course_id,json=courseId,proto3,oneof" json:"course_id,omitempty"`
	ChapterId     *string                `protobuf:"bytes,3,opt,name=chapter_id,json=chapterId,proto3,oneof" json:"chapter_id,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	OrderLesson   int32                  `protobuf:"varint,5,opt,name=order_lesson,json=orderLesson,proto3" json:"order_lesson,omitempty"`
	Slug          *string                `protobuf:"bytes,6,opt,name=slug,proto3,oneof" json:"slug,omitempty"`
	Description   *string                `protobuf:"bytes,7,opt,name=description,proto3,oneof" json:"description,omitempty"`
	FilePath      *string                `protobuf:"bytes,8,opt,name=file_path,json=filePath,proto3,oneof" json:"file_path,omitempty"`
	StorageLesson *string                `protobuf:"bytes,9,opt,name=storage_lesson,json=storageLesson,proto3,oneof" json:"storage_lesson,omitempty"`
	LessonType    *string                `protobuf:"bytes,10,opt,name=lesson_type,json=lessonType,proto3,oneof" json:"lesson_type,omitempty"`
	Volume        *string                `protobuf:"bytes,11,opt,name=volume,proto3,oneof" json:"volume,omitempty"`
	Duration      *string                `protobuf:"bytes,12,opt,name=duration,proto3,oneof" json:"duration,omitempty"`
	FileType      *string                `protobuf:"bytes,13,opt,name=file_type,json=fileType,proto3,oneof" json:"file_type,omitempty"`
	Downloadable  *string                `protobuf:"bytes,14,opt,name=downloadable,proto3,oneof" json:"downloadable,omitempty"`
	IsPreview     *int32                 `protobuf:"varint,15,opt,name=is_preview,json=isPreview,proto3,oneof" json:"is_preview,omitempty"`
	Status        *string                `protobuf:"bytes,16,opt,name=status,proto3,oneof" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateChapterLessonRequest) Reset() {
	*x = CreateChapterLessonRequest{}
	mi := &file_chapter_lesson_chapter_lesson_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateChapterLessonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChapterLessonRequest) ProtoMessage() {}

func (x *CreateChapterLessonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chapter_lesson_chapter_lesson_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChapterLessonRequest.ProtoReflect.Descriptor instead.
func (*CreateChapterLessonRequest) Descriptor() ([]byte, []int) {
	return file_chapter_lesson_chapter_lesson_proto_rawDescGZIP(), []int{3}
}

func (x *CreateChapterLessonRequest) GetInstructorId() string {
	if x != nil && x.InstructorId != nil {
		return *x.InstructorId
	}
	return ""
}

func (x *CreateChapterLessonRequest) GetCourseId() string {
	if x != nil && x.CourseId != nil {
		return *x.CourseId
	}
	return ""
}

func (x *CreateChapterLessonRequest) GetChapterId() string {
	if x != nil && x.ChapterId != nil {
		return *x.ChapterId
	}
	return ""
}

func (x *CreateChapterLessonRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateChapterLessonRequest) GetOrderLesson() int32 {
	if x != nil {
		return x.OrderLesson
	}
	return 0
}

func (x *CreateChapterLessonRequest) GetSlug() string {
	if x != nil && x.Slug != nil {
		return *x.Slug
	}
	return ""
}

func (x *CreateChapterLessonRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *CreateChapterLessonRequest) GetFilePath() string {
	if x != nil && x.FilePath != nil {
		return *x.FilePath
	}
	return ""
}

func (x *CreateChapterLessonRequest) GetStorageLesson() string {
	if x != nil && x.StorageLesson != nil {
		return *x.StorageLesson
	}
	return ""
}

func (x *CreateChapterLessonRequest) GetLessonType() string {
	if x != nil && x.LessonType != nil {
		return *x.LessonType
	}
	return ""
}

func (x *CreateChapterLessonRequest) GetVolume() string {
	if x != nil && x.Volume != nil {
		return *x.Volume
	}
	return ""
}

func (x *CreateChapterLessonRequest) GetDuration() string {
	if x != nil && x.Duration != nil {
		return *x.Duration
	}
	return ""
}

func (x *CreateChapterLessonRequest) GetFileType() string {
	if x != nil && x.FileType != nil {
		return *x.FileType
	}
	return ""
}

func (x *CreateChapterLessonRequest) GetDownloadable() string {
	if x != nil && x.Downloadable != nil {
		return *x.Downloadable
	}
	return ""
}

func (x *CreateChapterLessonRequest) GetIsPreview() int32 {
	if x != nil && x.IsPreview != nil {
		return *x.IsPreview
	}
	return 0
}

func (x *CreateChapterLessonRequest) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

type CreateChapterLessonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *common.BaseResponse   `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateChapterLessonResponse) Reset() {
	*x = CreateChapterLessonResponse{}
	mi := &file_chapter_lesson_chapter_lesson_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateChapterLessonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChapterLessonResponse) ProtoMessage() {}

func (x *CreateChapterLessonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chapter_lesson_chapter_lesson_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChapterLessonResponse.ProtoReflect.Descriptor instead.
func (*CreateChapterLessonResponse) Descriptor() ([]byte, []int) {
	return file_chapter_lesson_chapter_lesson_proto_rawDescGZIP(), []int{4}
}

func (x *CreateChapterLessonResponse) GetBase() *common.BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *CreateChapterLessonResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DetailChapterLessonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FieldMask     *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=field_mask,json=fieldMask,proto3" json:"field_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetailChapterLessonRequest) Reset() {
	*x = DetailChapterLessonRequest{}
	mi := &file_chapter_lesson_chapter_lesson_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetailChapterLessonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetailChapterLessonRequest) ProtoMessage() {}

func (x *DetailChapterLessonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chapter_lesson_chapter_lesson_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetailChapterLessonRequest.ProtoReflect.Descriptor instead.
func (*DetailChapterLessonRequest) Descriptor() ([]byte, []int) {
	return file_chapter_lesson_chapter_lesson_proto_rawDescGZIP(), []int{5}
}

func (x *DetailChapterLessonRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DetailChapterLessonRequest) GetFieldMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.FieldMask
	}
	return nil
}

type DetailChapterLessonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *common.BaseResponse   `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	ChapterId     *string                `protobuf:"bytes,3,opt,name=chapter_id,json=chapterId,proto3,oneof" json:"chapter_id,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	OrderLesson   int32                  `protobuf:"varint,5,opt,name=order_lesson,json=orderLesson,proto3" json:"order_lesson,omitempty"`
	Slug          *string                `protobuf:"bytes,6,opt,name=slug,proto3,oneof" json:"slug,omitempty"`
	Description   *string                `protobuf:"bytes,7,opt,name=description,proto3,oneof" json:"description,omitempty"`
	FilePath      *string                `protobuf:"bytes,8,opt,name=file_path,json=filePath,proto3,oneof" json:"file_path,omitempty"`
	StorageLesson *string                `protobuf:"bytes,9,opt,name=storage_lesson,json=storageLesson,proto3,oneof" json:"storage_lesson,omitempty"`
	LessonType    *string                `protobuf:"bytes,10,opt,name=lesson_type,json=lessonType,proto3,oneof" json:"lesson_type,omitempty"`
	Volume        *string                `protobuf:"bytes,11,opt,name=volume,proto3,oneof" json:"volume,omitempty"`
	Duration      *string                `protobuf:"bytes,12,opt,name=duration,proto3,oneof" json:"duration,omitempty"`
	FileType      *string                `protobuf:"bytes,13,opt,name=file_type,json=fileType,proto3,oneof" json:"file_type,omitempty"`
	Downloadable  *string                `protobuf:"bytes,14,opt,name=downloadable,proto3,oneof" json:"downloadable,omitempty"`
	IsPreview     *int32                 `protobuf:"varint,15,opt,name=is_preview,json=isPreview,proto3,oneof" json:"is_preview,omitempty"`
	Status        *string                `protobuf:"bytes,16,opt,name=status,proto3,oneof" json:"status,omitempty"`
	InstructorId  *string                `protobuf:"bytes,17,opt,name=instructor_id,json=instructorId,proto3,oneof" json:"instructor_id,omitempty"`
	CourseId      *string                `protobuf:"bytes,18,opt,name=course_id,json=courseId,proto3,oneof" json:"course_id,omitempty"`
	CreatedAt     *string                `protobuf:"bytes,19,opt,name=created_at,json=createdAt,proto3,oneof" json:"created_at,omitempty"`
	CreatedBy     *string                `protobuf:"bytes,20,opt,name=created_by,json=createdBy,proto3,oneof" json:"created_by,omitempty"`
	DeletedBy     *string                `protobuf:"bytes,21,opt,name=deleted_by,json=deletedBy,proto3,oneof" json:"deleted_by,omitempty"`
	UpdatedAt     *string                `protobuf:"bytes,22,opt,name=updated_at,json=updatedAt,proto3,oneof" json:"updated_at,omitempty"`
	UpdatedBy     *string                `protobuf:"bytes,23,opt,name=updated_by,json=updatedBy,proto3,oneof" json:"updated_by,omitempty"`
	DeletedAt     *string                `protobuf:"bytes,24,opt,name=deleted_at,json=deletedAt,proto3,oneof" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetailChapterLessonResponse) Reset() {
	*x = DetailChapterLessonResponse{}
	mi := &file_chapter_lesson_chapter_lesson_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetailChapterLessonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetailChapterLessonResponse) ProtoMessage() {}

func (x *DetailChapterLessonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chapter_lesson_chapter_lesson_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetailChapterLessonResponse.ProtoReflect.Descriptor instead.
func (*DetailChapterLessonResponse) Descriptor() ([]byte, []int) {
	return file_chapter_lesson_chapter_lesson_proto_rawDescGZIP(), []int{6}
}

func (x *DetailChapterLessonResponse) GetBase() *common.BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *DetailChapterLessonResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DetailChapterLessonResponse) GetChapterId() string {
	if x != nil && x.ChapterId != nil {
		return *x.ChapterId
	}
	return ""
}

func (x *DetailChapterLessonResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *DetailChapterLessonResponse) GetOrderLesson() int32 {
	if x != nil {
		return x.OrderLesson
	}
	return 0
}

func (x *DetailChapterLessonResponse) GetSlug() string {
	if x != nil && x.Slug != nil {
		return *x.Slug
	}
	return ""
}

func (x *DetailChapterLessonResponse) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *DetailChapterLessonResponse) GetFilePath() string {
	if x != nil && x.FilePath != nil {
		return *x.FilePath
	}
	return ""
}

func (x *DetailChapterLessonResponse) GetStorageLesson() string {
	if x != nil && x.StorageLesson != nil {
		return *x.StorageLesson
	}
	return ""
}

func (x *DetailChapterLessonResponse) GetLessonType() string {
	if x != nil && x.LessonType != nil {
		return *x.LessonType
	}
	return ""
}

func (x *DetailChapterLessonResponse) GetVolume() string {
	if x != nil && x.Volume != nil {
		return *x.Volume
	}
	return ""
}

func (x *DetailChapterLessonResponse) GetDuration() string {
	if x != nil && x.Duration != nil {
		return *x.Duration
	}
	return ""
}

func (x *DetailChapterLessonResponse) GetFileType() string {
	if x != nil && x.FileType != nil {
		return *x.FileType
	}
	return ""
}

func (x *DetailChapterLessonResponse) GetDownloadable() string {
	if x != nil && x.Downloadable != nil {
		return *x.Downloadable
	}
	return ""
}

func (x *DetailChapterLessonResponse) GetIsPreview() int32 {
	if x != nil && x.IsPreview != nil {
		return *x.IsPreview
	}
	return 0
}

func (x *DetailChapterLessonResponse) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

func (x *DetailChapterLessonResponse) GetInstructorId() string {
	if x != nil && x.InstructorId != nil {
		return *x.InstructorId
	}
	return ""
}

func (x *DetailChapterLessonResponse) GetCourseId() string {
	if x != nil && x.CourseId != nil {
		return *x.CourseId
	}
	return ""
}

func (x *DetailChapterLessonResponse) GetCreatedAt() string {
	if x != nil && x.CreatedAt != nil {
		return *x.CreatedAt
	}
	return ""
}

func (x *DetailChapterLessonResponse) GetCreatedBy() string {
	if x != nil && x.CreatedBy != nil {
		return *x.CreatedBy
	}
	return ""
}

func (x *DetailChapterLessonResponse) GetDeletedBy() string {
	if x != nil && x.DeletedBy != nil {
		return *x.DeletedBy
	}
	return ""
}

func (x *DetailChapterLessonResponse) GetUpdatedAt() string {
	if x != nil && x.UpdatedAt != nil {
		return *x.UpdatedAt
	}
	return ""
}

func (x *DetailChapterLessonResponse) GetUpdatedBy() string {
	if x != nil && x.UpdatedBy != nil {
		return *x.UpdatedBy
	}
	return ""
}

func (x *DetailChapterLessonResponse) GetDeletedAt() string {
	if x != nil && x.DeletedAt != nil {
		return *x.DeletedAt
	}
	return ""
}

type EditChapterLessonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CourseId      *string                `protobuf:"bytes,2,opt,name=course_id,json=courseId,proto3,oneof" json:"course_id,omitempty"`
	ChapterId     *string                `protobuf:"bytes,3,opt,name=chapter_id,json=chapterId,proto3,oneof" json:"chapter_id,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	OrderLesson   int32                  `protobuf:"varint,5,opt,name=order_lesson,json=orderLesson,proto3" json:"order_lesson,omitempty"`
	Slug          *string                `protobuf:"bytes,6,opt,name=slug,proto3,oneof" json:"slug,omitempty"`
	Description   *string                `protobuf:"bytes,7,opt,name=description,proto3,oneof" json:"description,omitempty"`
	FilePath      *string                `protobuf:"bytes,8,opt,name=file_path,json=filePath,proto3,oneof" json:"file_path,omitempty"`
	StorageLesson *string                `protobuf:"bytes,9,opt,name=storage_lesson,json=storageLesson,proto3,oneof" json:"storage_lesson,omitempty"`
	LessonType    *string                `protobuf:"bytes,10,opt,name=lesson_type,json=lessonType,proto3,oneof" json:"lesson_type,omitempty"`
	Volume        *string                `protobuf:"bytes,11,opt,name=volume,proto3,oneof" json:"volume,omitempty"`
	Duration      *string                `protobuf:"bytes,12,opt,name=duration,proto3,oneof" json:"duration,omitempty"`
	FileType      *string                `protobuf:"bytes,13,opt,name=file_type,json=fileType,proto3,oneof" json:"file_type,omitempty"`
	Downloadable  *string                `protobuf:"bytes,14,opt,name=downloadable,proto3,oneof" json:"downloadable,omitempty"`
	IsPreview     *int32                 `protobuf:"varint,15,opt,name=is_preview,json=isPreview,proto3,oneof" json:"is_preview,omitempty"`
	Status        *string                `protobuf:"bytes,16,opt,name=status,proto3,oneof" json:"status,omitempty"`
	InstructorId  *string                `protobuf:"bytes,17,opt,name=instructor_id,json=instructorId,proto3,oneof" json:"instructor_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditChapterLessonRequest) Reset() {
	*x = EditChapterLessonRequest{}
	mi := &file_chapter_lesson_chapter_lesson_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditChapterLessonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditChapterLessonRequest) ProtoMessage() {}

func (x *EditChapterLessonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chapter_lesson_chapter_lesson_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditChapterLessonRequest.ProtoReflect.Descriptor instead.
func (*EditChapterLessonRequest) Descriptor() ([]byte, []int) {
	return file_chapter_lesson_chapter_lesson_proto_rawDescGZIP(), []int{7}
}

func (x *EditChapterLessonRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EditChapterLessonRequest) GetCourseId() string {
	if x != nil && x.CourseId != nil {
		return *x.CourseId
	}
	return ""
}

func (x *EditChapterLessonRequest) GetChapterId() string {
	if x != nil && x.ChapterId != nil {
		return *x.ChapterId
	}
	return ""
}

func (x *EditChapterLessonRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *EditChapterLessonRequest) GetOrderLesson() int32 {
	if x != nil {
		return x.OrderLesson
	}
	return 0
}

func (x *EditChapterLessonRequest) GetSlug() string {
	if x != nil && x.Slug != nil {
		return *x.Slug
	}
	return ""
}

func (x *EditChapterLessonRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *EditChapterLessonRequest) GetFilePath() string {
	if x != nil && x.FilePath != nil {
		return *x.FilePath
	}
	return ""
}

func (x *EditChapterLessonRequest) GetStorageLesson() string {
	if x != nil && x.StorageLesson != nil {
		return *x.StorageLesson
	}
	return ""
}

func (x *EditChapterLessonRequest) GetLessonType() string {
	if x != nil && x.LessonType != nil {
		return *x.LessonType
	}
	return ""
}

func (x *EditChapterLessonRequest) GetVolume() string {
	if x != nil && x.Volume != nil {
		return *x.Volume
	}
	return ""
}

func (x *EditChapterLessonRequest) GetDuration() string {
	if x != nil && x.Duration != nil {
		return *x.Duration
	}
	return ""
}

func (x *EditChapterLessonRequest) GetFileType() string {
	if x != nil && x.FileType != nil {
		return *x.FileType
	}
	return ""
}

func (x *EditChapterLessonRequest) GetDownloadable() string {
	if x != nil && x.Downloadable != nil {
		return *x.Downloadable
	}
	return ""
}

func (x *EditChapterLessonRequest) GetIsPreview() int32 {
	if x != nil && x.IsPreview != nil {
		return *x.IsPreview
	}
	return 0
}

func (x *EditChapterLessonRequest) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

func (x *EditChapterLessonRequest) GetInstructorId() string {
	if x != nil && x.InstructorId != nil {
		return *x.InstructorId
	}
	return ""
}

type EditChapterLessonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *common.BaseResponse   `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditChapterLessonResponse) Reset() {
	*x = EditChapterLessonResponse{}
	mi := &file_chapter_lesson_chapter_lesson_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditChapterLessonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditChapterLessonResponse) ProtoMessage() {}

func (x *EditChapterLessonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chapter_lesson_chapter_lesson_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditChapterLessonResponse.ProtoReflect.Descriptor instead.
func (*EditChapterLessonResponse) Descriptor() ([]byte, []int) {
	return file_chapter_lesson_chapter_lesson_proto_rawDescGZIP(), []int{8}
}

func (x *EditChapterLessonResponse) GetBase() *common.BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *EditChapterLessonResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteChapterLessonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteChapterLessonRequest) Reset() {
	*x = DeleteChapterLessonRequest{}
	mi := &file_chapter_lesson_chapter_lesson_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteChapterLessonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteChapterLessonRequest) ProtoMessage() {}

func (x *DeleteChapterLessonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chapter_lesson_chapter_lesson_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteChapterLessonRequest.ProtoReflect.Descriptor instead.
func (*DeleteChapterLessonRequest) Descriptor() ([]byte, []int) {
	return file_chapter_lesson_chapter_lesson_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteChapterLessonRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteChapterLessonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *common.BaseResponse   `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteChapterLessonResponse) Reset() {
	*x = DeleteChapterLessonResponse{}
	mi := &file_chapter_lesson_chapter_lesson_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteChapterLessonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteChapterLessonResponse) ProtoMessage() {}

func (x *DeleteChapterLessonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chapter_lesson_chapter_lesson_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteChapterLessonResponse.ProtoReflect.Descriptor instead.
func (*DeleteChapterLessonResponse) Descriptor() ([]byte, []int) {
	return file_chapter_lesson_chapter_lesson_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteChapterLessonResponse) GetBase() *common.BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

var File_chapter_lesson_chapter_lesson_proto protoreflect.FileDescriptor

const file_chapter_lesson_chapter_lesson_proto_rawDesc = "" +
	"\n" +
	"#chapter_lesson/chapter_lesson.proto\x12\x0echapter_lesson\x1a\x1acommon/base_response.proto\x1a\x1bbuf/validate/validate.proto\x1a google/protobuf/field_mask.proto\"v\n" +
	"\x1aGetAllChapterLessonRequest\x12\x1d\n" +
	"\n" +
	"chapter_id\x18\x01 \x01(\tR\tchapterId\x129\n" +
	"\n" +
	"field_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\tfieldMask\"}\n" +
	"\x1bGetAllChapterLessonResponse\x12(\n" +
	"\x04base\x18\x01 \x01(\v2\x14.common.BaseResponseR\x04base\x124\n" +
	"\alessons\x18\x02 \x03(\v2\x1a.chapter_lesson.LessonInfoR\alessons\"\xd8\a\n" +
	"\n" +
	"LessonInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x124\n" +
	"\rinstructor_id\x18\x02 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01H\x00R\finstructorId\x88\x01\x01\x12,\n" +
	"\tcourse_id\x18\x03 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01H\x01R\bcourseId\x88\x01\x01\x12.\n" +
	"\n" +
	"chapter_id\x18\x04 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01H\x02R\tchapterId\x88\x01\x01\x12%\n" +
	"\x05title\x18\x05 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01H\x03R\x05title\x88\x01\x01\x12/\n" +
	"\forder_lesson\x18\x06 \x01(\x05B\a\xbaH\x04\x1a\x02(\x00H\x04R\vorderLesson\x88\x01\x01\x12!\n" +
	"\x04slug\x18\a \x01(\tB\b\xbaH\x05r\x03\x18\xff\x01H\x05R\x04slug\x88\x01\x01\x12*\n" +
	"\tfile_path\x18\b \x01(\tB\b\xbaH\x05r\x03\x18\xff\x01H\x06R\bfilePath\x88\x01\x01\x124\n" +
	"\x0estorage_lesson\x18\t \x01(\tB\b\xbaH\x05r\x03\x18\xff\x01H\aR\rstorageLesson\x88\x01\x01\x12.\n" +
	"\vlesson_type\x18\n" +
	" \x01(\tB\b\xbaH\x05r\x03\x18\xff\x01H\bR\n" +
	"lessonType\x88\x01\x01\x12%\n" +
	"\x06volume\x18\v \x01(\tB\b\xbaH\x05r\x03\x18\xff\x01H\tR\x06volume\x88\x01\x01\x12)\n" +
	"\bduration\x18\f \x01(\tB\b\xbaH\x05r\x03\x18\xff\x01H\n" +
	"R\bduration\x88\x01\x01\x12*\n" +
	"\tfile_type\x18\r \x01(\tB\b\xbaH\x05r\x03\x18\xff\x01H\vR\bfileType\x88\x01\x01\x121\n" +
	"\fdownloadable\x18\x0e \x01(\tB\b\xbaH\x05r\x03\x18\xff\x01H\fR\fdownloadable\x88\x01\x01\x12+\n" +
	"\n" +
	"is_preview\x18\x0f \x01(\x05B\a\xbaH\x04\x1a\x02(\x00H\rR\tisPreview\x88\x01\x01\x12%\n" +
	"\x06status\x18\x10 \x01(\tB\b\xbaH\x05r\x03\x18\xff\x01H\x0eR\x06status\x88\x01\x01\x12/\n" +
	"\vdescription\x18\x11 \x01(\tB\b\xbaH\x05r\x03\x18\xff\x01H\x0fR\vdescription\x88\x01\x01B\x10\n" +
	"\x0e_instructor_idB\f\n" +
	"\n" +
	"_course_idB\r\n" +
	"\v_chapter_idB\b\n" +
	"\x06_titleB\x0f\n" +
	"\r_order_lessonB\a\n" +
	"\x05_slugB\f\n" +
	"\n" +
	"_file_pathB\x11\n" +
	"\x0f_storage_lessonB\x0e\n" +
	"\f_lesson_typeB\t\n" +
	"\a_volumeB\v\n" +
	"\t_durationB\f\n" +
	"\n" +
	"_file_typeB\x0f\n" +
	"\r_downloadableB\r\n" +
	"\v_is_previewB\t\n" +
	"\a_statusB\x0e\n" +
	"\f_description\"\xb3\a\n" +
	"\x1aCreateChapterLessonRequest\x124\n" +
	"\rinstructor_id\x18\x01 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01H\x00R\finstructorId\x88\x01\x01\x12,\n" +
	"\tcourse_id\x18\x02 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01H\x01R\bcourseId\x88\x01\x01\x12.\n" +
	"\n" +
	"chapter_id\x18\x03 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01H\x02R\tchapterId\x88\x01\x01\x12 \n" +
	"\x05title\x18\x04 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01R\x05title\x12*\n" +
	"\forder_lesson\x18\x05 \x01(\x05B\a\xbaH\x04\x1a\x02(\x00R\vorderLesson\x12!\n" +
	"\x04slug\x18\x06 \x01(\tB\b\xbaH\x05r\x03\x18\xff\x01H\x03R\x04slug\x88\x01\x01\x12/\n" +
	"\vdescription\x18\a \x01(\tB\b\xbaH\x05r\x03\x18\xff\x01H\x04R\vdescription\x88\x01\x01\x12*\n" +
	"\tfile_path\x18\b \x01(\tB\b\xbaH\x05r\x03\x18\xff\x01H\x05R\bfilePath\x88\x01\x01\x124\n" +
	"\x0estorage_lesson\x18\t \x01(\tB\b\xbaH\x05r\x03\x18\xff\x01H\x06R\rstorageLesson\x88\x01\x01\x12.\n" +
	"\vlesson_type\x18\n" +
	" \x01(\tB\b\xbaH\x05r\x03\x18\xff\x01H\aR\n" +
	"lessonType\x88\x01\x01\x12%\n" +
	"\x06volume\x18\v \x01(\tB\b\xbaH\x05r\x03\x18\xff\x01H\bR\x06volume\x88\x01\x01\x12)\n" +
	"\bduration\x18\f \x01(\tB\b\xbaH\x05r\x03\x18\xff\x01H\tR\bduration\x88\x01\x01\x12*\n" +
	"\tfile_type\x18\r \x01(\tB\b\xbaH\x05r\x03\x18\xff\x01H\n" +
	"R\bfileType\x88\x01\x01\x121\n" +
	"\fdownloadable\x18\x0e \x01(\tB\b\xbaH\x05r\x03\x18\xff\x01H\vR\fdownloadable\x88\x01\x01\x12+\n" +
	"\n" +
	"is_preview\x18\x0f \x01(\x05B\a\xbaH\x04\x1a\x02(\x00H\fR\tisPreview\x88\x01\x01\x12%\n" +
	"\x06status\x18\x10 \x01(\tB\b\xbaH\x05r\x03\x18\xff\x01H\rR\x06status\x88\x01\x01B\x10\n" +
	"\x0e_instructor_idB\f\n" +
	"\n" +
	"_course_idB\r\n" +
	"\v_chapter_idB\a\n" +
	"\x05_slugB\x0e\n" +
	"\f_descriptionB\f\n" +
	"\n" +
	"_file_pathB\x11\n" +
	"\x0f_storage_lessonB\x0e\n" +
	"\f_lesson_typeB\t\n" +
	"\a_volumeB\v\n" +
	"\t_durationB\f\n" +
	"\n" +
	"_file_typeB\x0f\n" +
	"\r_downloadableB\r\n" +
	"\v_is_previewB\t\n" +
	"\a_status\"W\n" +
	"\x1bCreateChapterLessonResponse\x12(\n" +
	"\x04base\x18\x01 \x01(\v2\x14.common.BaseResponseR\x04base\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"s\n" +
	"\x1aDetailChapterLessonRequest\x12\x1a\n" +
	"\x02id\x18\x01 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01R\x02id\x129\n" +
	"\n" +
	"field_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\tfieldMask\"\xa0\n" +
	"\n" +
	"\x1bDetailChapterLessonResponse\x12(\n" +
	"\x04base\x18\x01 \x01(\v2\x14.common.BaseResponseR\x04base\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12.\n" +
	"\n" +
	"chapter_id\x18\x03 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01H\x00R\tchapterId\x88\x01\x01\x12 \n" +
	"\x05title\x18\x04 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01R\x05title\x12*\n" +
	"\forder_lesson\x18\x05 \x01(\x05B\a\xbaH\x04\x1a\x02(\x00R\vorderLesson\x12!\n" +
	"\x04slug\x18\x06 \x01(\tB\b\xbaH\x05r\x03\x18\xff\x01H\x01R\x04slug\x88\x01\x01\x12/\n" +
	"\vdescription\x18\a \x01(\tB\b\xbaH\x05r\x03\x18\xff\x01H\x02R\vdescription\x88\x01\x01\x12*\n" +
	"\tfile_path\x18\b \x01(\tB\b\xbaH\x05r\x03\x18\xff\x01H\x03R\bfilePath\x88\x01\x01\x124\n" +
	"\x0estorage_lesson\x18\t \x01(\tB\b\xbaH\x05r\x03\x18\xff\x01H\x04R\rstorageLesson\x88\x01\x01\x12.\n" +
	"\vlesson_type\x18\n" +
	" \x01(\tB\b\xbaH\x05r\x03\x18\xff\x01H\x05R\n" +
	"lessonType\x88\x01\x01\x12%\n" +
	"\x06volume\x18\v \x01(\tB\b\xbaH\x05r\x03\x18\xff\x01H\x06R\x06volume\x88\x01\x01\x12)\n" +
	"\bduration\x18\f \x01(\tB\b\xbaH\x05r\x03\x18\xff\x01H\aR\bduration\x88\x01\x01\x12*\n" +
	"\tfile_type\x18\r \x01(\tB\b\xbaH\x05r\x03\x18\xff\x01H\bR\bfileType\x88\x01\x01\x121\n" +
	"\fdownloadable\x18\x0e \x01(\tB\b\xbaH\x05r\x03\x18\xff\x01H\tR\fdownloadable\x88\x01\x01\x12+\n" +
	"\n" +
	"is_preview\x18\x0f \x01(\x05B\a\xbaH\x04\x1a\x02(\x00H\n" +
	"R\tisPreview\x88\x01\x01\x12%\n" +
	"\x06status\x18\x10 \x01(\tB\b\xbaH\x05r\x03\x18\xff\x01H\vR\x06status\x88\x01\x01\x124\n" +
	"\rinstructor_id\x18\x11 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01H\fR\finstructorId\x88\x01\x01\x12,\n" +
	"\tcourse_id\x18\x12 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01H\rR\bcourseId\x88\x01\x01\x12\"\n" +
	"\n" +
	"created_at\x18\x13 \x01(\tH\x0eR\tcreatedAt\x88\x01\x01\x12\"\n" +
	"\n" +
	"created_by\x18\x14 \x01(\tH\x0fR\tcreatedBy\x88\x01\x01\x12\"\n" +
	"\n" +
	"deleted_by\x18\x15 \x01(\tH\x10R\tdeletedBy\x88\x01\x01\x12\"\n" +
	"\n" +
	"updated_at\x18\x16 \x01(\tH\x11R\tupdatedAt\x88\x01\x01\x12\"\n" +
	"\n" +
	"updated_by\x18\x17 \x01(\tH\x12R\tupdatedBy\x88\x01\x01\x12\"\n" +
	"\n" +
	"deleted_at\x18\x18 \x01(\tH\x13R\tdeletedAt\x88\x01\x01B\r\n" +
	"\v_chapter_idB\a\n" +
	"\x05_slugB\x0e\n" +
	"\f_descriptionB\f\n" +
	"\n" +
	"_file_pathB\x11\n" +
	"\x0f_storage_lessonB\x0e\n" +
	"\f_lesson_typeB\t\n" +
	"\a_volumeB\v\n" +
	"\t_durationB\f\n" +
	"\n" +
	"_file_typeB\x0f\n" +
	"\r_downloadableB\r\n" +
	"\v_is_previewB\t\n" +
	"\a_statusB\x10\n" +
	"\x0e_instructor_idB\f\n" +
	"\n" +
	"_course_idB\r\n" +
	"\v_created_atB\r\n" +
	"\v_created_byB\r\n" +
	"\v_deleted_byB\r\n" +
	"\v_updated_atB\r\n" +
	"\v_updated_byB\r\n" +
	"\v_deleted_at\"\xcd\a\n" +
	"\x18EditChapterLessonRequest\x12\x1a\n" +
	"\x02id\x18\x01 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01R\x02id\x12,\n" +
	"\tcourse_id\x18\x02 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01H\x00R\bcourseId\x88\x01\x01\x12.\n" +
	"\n" +
	"chapter_id\x18\x03 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01H\x01R\tchapterId\x88\x01\x01\x12 \n" +
	"\x05title\x18\x04 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01R\x05title\x12*\n" +
	"\forder_lesson\x18\x05 \x01(\x05B\a\xbaH\x04\x1a\x02(\x00R\vorderLesson\x12!\n" +
	"\x04slug\x18\x06 \x01(\tB\b\xbaH\x05r\x03\x18\xff\x01H\x02R\x04slug\x88\x01\x01\x12/\n" +
	"\vdescription\x18\a \x01(\tB\b\xbaH\x05r\x03\x18\xff\x01H\x03R\vdescription\x88\x01\x01\x12*\n" +
	"\tfile_path\x18\b \x01(\tB\b\xbaH\x05r\x03\x18\xff\x01H\x04R\bfilePath\x88\x01\x01\x124\n" +
	"\x0estorage_lesson\x18\t \x01(\tB\b\xbaH\x05r\x03\x18\xff\x01H\x05R\rstorageLesson\x88\x01\x01\x12.\n" +
	"\vlesson_type\x18\n" +
	" \x01(\tB\b\xbaH\x05r\x03\x18\xff\x01H\x06R\n" +
	"lessonType\x88\x01\x01\x12%\n" +
	"\x06volume\x18\v \x01(\tB\b\xbaH\x05r\x03\x18\xff\x01H\aR\x06volume\x88\x01\x01\x12)\n" +
	"\bduration\x18\f \x01(\tB\b\xbaH\x05r\x03\x18\xff\x01H\bR\bduration\x88\x01\x01\x12*\n" +
	"\tfile_type\x18\r \x01(\tB\b\xbaH\x05r\x03\x18\xff\x01H\tR\bfileType\x88\x01\x01\x121\n" +
	"\fdownloadable\x18\x0e \x01(\tB\b\xbaH\x05r\x03\x18\xff\x01H\n" +
	"R\fdownloadable\x88\x01\x01\x12+\n" +
	"\n" +
	"is_preview\x18\x0f \x01(\x05B\a\xbaH\x04\x1a\x02(\x00H\vR\tisPreview\x88\x01\x01\x12%\n" +
	"\x06status\x18\x10 \x01(\tB\b\xbaH\x05r\x03\x18\xff\x01H\fR\x06status\x88\x01\x01\x124\n" +
	"\rinstructor_id\x18\x11 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01H\rR\finstructorId\x88\x01\x01B\f\n" +
	"\n" +
	"_course_idB\r\n" +
	"\v_chapter_idB\a\n" +
	"\x05_slugB\x0e\n" +
	"\f_descriptionB\f\n" +
	"\n" +
	"_file_pathB\x11\n" +
	"\x0f_storage_lessonB\x0e\n" +
	"\f_lesson_typeB\t\n" +
	"\a_volumeB\v\n" +
	"\t_durationB\f\n" +
	"\n" +
	"_file_typeB\x0f\n" +
	"\r_downloadableB\r\n" +
	"\v_is_previewB\t\n" +
	"\a_statusB\x10\n" +
	"\x0e_instructor_id\"U\n" +
	"\x19EditChapterLessonResponse\x12(\n" +
	"\x04base\x18\x01 \x01(\v2\x14.common.BaseResponseR\x04base\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"8\n" +
	"\x1aDeleteChapterLessonRequest\x12\x1a\n" +
	"\x02id\x18\x01 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01R\x02id\"G\n" +
	"\x1bDeleteChapterLessonResponse\x12(\n" +
	"\x04base\x18\x01 \x01(\v2\x14.common.BaseResponseR\x04base2\xc0\x04\n" +
	"\x14ChapterLessonService\x12n\n" +
	"\x13GetAllChapterLesson\x12*.chapter_lesson.GetAllChapterLessonRequest\x1a+.chapter_lesson.GetAllChapterLessonResponse\x12n\n" +
	"\x13CreateChapterLesson\x12*.chapter_lesson.CreateChapterLessonRequest\x1a+.chapter_lesson.CreateChapterLessonResponse\x12n\n" +
	"\x13DetailChapterLesson\x12*.chapter_lesson.DetailChapterLessonRequest\x1a+.chapter_lesson.DetailChapterLessonResponse\x12h\n" +
	"\x11EditChapterLesson\x12(.chapter_lesson.EditChapterLessonRequest\x1a).chapter_lesson.EditChapterLessonResponse\x12n\n" +
	"\x13DeleteChapterLesson\x12*.chapter_lesson.DeleteChapterLessonRequest\x1a+.chapter_lesson.DeleteChapterLessonResponseB2Z0github.com/abu-umair/be-lms-go/pb/chapter_lessonb\x06proto3"

var (
	file_chapter_lesson_chapter_lesson_proto_rawDescOnce sync.Once
	file_chapter_lesson_chapter_lesson_proto_rawDescData []byte
)

func file_chapter_lesson_chapter_lesson_proto_rawDescGZIP() []byte {
	file_chapter_lesson_chapter_lesson_proto_rawDescOnce.Do(func() {
		file_chapter_lesson_chapter_lesson_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chapter_lesson_chapter_lesson_proto_rawDesc), len(file_chapter_lesson_chapter_lesson_proto_rawDesc)))
	})
	return file_chapter_lesson_chapter_lesson_proto_rawDescData
}

var file_chapter_lesson_chapter_lesson_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_chapter_lesson_chapter_lesson_proto_goTypes = []any{
	(*GetAllChapterLessonRequest)(nil),  // 0: chapter_lesson.GetAllChapterLessonRequest
	(*GetAllChapterLessonResponse)(nil), // 1: chapter_lesson.GetAllChapterLessonResponse
	(*LessonInfo)(nil),                  // 2: chapter_lesson.LessonInfo
	(*CreateChapterLessonRequest)(nil),  // 3: chapter_lesson.CreateChapterLessonRequest
	(*CreateChapterLessonResponse)(nil), // 4: chapter_lesson.CreateChapterLessonResponse
	(*DetailChapterLessonRequest)(nil),  // 5: chapter_lesson.DetailChapterLessonRequest
	(*DetailChapterLessonResponse)(nil), // 6: chapter_lesson.DetailChapterLessonResponse
	(*EditChapterLessonRequest)(nil),    // 7: chapter_lesson.EditChapterLessonRequest
	(*EditChapterLessonResponse)(nil),   // 8: chapter_lesson.EditChapterLessonResponse
	(*DeleteChapterLessonRequest)(nil),  // 9: chapter_lesson.DeleteChapterLessonRequest
	(*DeleteChapterLessonResponse)(nil), // 10: chapter_lesson.DeleteChapterLessonResponse
	(*fieldmaskpb.FieldMask)(nil),       // 11: google.protobuf.FieldMask
	(*common.BaseResponse)(nil),         // 12: common.BaseResponse
}
var file_chapter_lesson_chapter_lesson_proto_depIdxs = []int32{
	11, // 0: chapter_lesson.GetAllChapterLessonRequest.field_mask:type_name -> google.protobuf.FieldMask
	12, // 1: chapter_lesson.GetAllChapterLessonResponse.base:type_name -> common.BaseResponse
	2,  // 2: chapter_lesson.GetAllChapterLessonResponse.lessons:type_name -> chapter_lesson.LessonInfo
	12, // 3: chapter_lesson.CreateChapterLessonResponse.base:type_name -> common.BaseResponse
	11, // 4: chapter_lesson.DetailChapterLessonRequest.field_mask:type_name -> google.protobuf.FieldMask
	12, // 5: chapter_lesson.DetailChapterLessonResponse.base:type_name -> common.BaseResponse
	12, // 6: chapter_lesson.EditChapterLessonResponse.base:type_name -> common.BaseResponse
	12, // 7: chapter_lesson.DeleteChapterLessonResponse.base:type_name -> common.BaseResponse
	0,  // 8: chapter_lesson.ChapterLessonService.GetAllChapterLesson:input_type -> chapter_lesson.GetAllChapterLessonRequest
	3,  // 9: chapter_lesson.ChapterLessonService.CreateChapterLesson:input_type -> chapter_lesson.CreateChapterLessonRequest
	5,  // 10: chapter_lesson.ChapterLessonService.DetailChapterLesson:input_type -> chapter_lesson.DetailChapterLessonRequest
	7,  // 11: chapter_lesson.ChapterLessonService.EditChapterLesson:input_type -> chapter_lesson.EditChapterLessonRequest
	9,  // 12: chapter_lesson.ChapterLessonService.DeleteChapterLesson:input_type -> chapter_lesson.DeleteChapterLessonRequest
	1,  // 13: chapter_lesson.ChapterLessonService.GetAllChapterLesson:output_type -> chapter_lesson.GetAllChapterLessonResponse
	4,  // 14: chapter_lesson.ChapterLessonService.CreateChapterLesson:output_type -> chapter_lesson.CreateChapterLessonResponse
	6,  // 15: chapter_lesson.ChapterLessonService.DetailChapterLesson:output_type -> chapter_lesson.DetailChapterLessonResponse
	8,  // 16: chapter_lesson.ChapterLessonService.EditChapterLesson:output_type -> chapter_lesson.EditChapterLessonResponse
	10, // 17: chapter_lesson.ChapterLessonService.DeleteChapterLesson:output_type -> chapter_lesson.DeleteChapterLessonResponse
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_chapter_lesson_chapter_lesson_proto_init() }
func file_chapter_lesson_chapter_lesson_proto_init() {
	if File_chapter_lesson_chapter_lesson_proto != nil {
		return
	}
	file_chapter_lesson_chapter_lesson_proto_msgTypes[2].OneofWrappers = []any{}
	file_chapter_lesson_chapter_lesson_proto_msgTypes[3].OneofWrappers = []any{}
	file_chapter_lesson_chapter_lesson_proto_msgTypes[6].OneofWrappers = []any{}
	file_chapter_lesson_chapter_lesson_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chapter_lesson_chapter_lesson_proto_rawDesc), len(file_chapter_lesson_chapter_lesson_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chapter_lesson_chapter_lesson_proto_goTypes,
		DependencyIndexes: file_chapter_lesson_chapter_lesson_proto_depIdxs,
		MessageInfos:      file_chapter_lesson_chapter_lesson_proto_msgTypes,
	}.Build()
	File_chapter_lesson_chapter_lesson_proto = out.File
	file_chapter_lesson_chapter_lesson_proto_goTypes = nil
	file_chapter_lesson_chapter_lesson_proto_depIdxs = nil
}
