// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "chapter_lesson/chapter_lesson.proto" (package "chapter_lesson", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { ChapterLessonService } from "./chapter_lesson";
import type { DeleteChapterLessonResponse } from "./chapter_lesson";
import type { DeleteChapterLessonRequest } from "./chapter_lesson";
import type { EditChapterLessonResponse } from "./chapter_lesson";
import type { EditChapterLessonRequest } from "./chapter_lesson";
import type { DetailChapterLessonResponse } from "./chapter_lesson";
import type { DetailChapterLessonRequest } from "./chapter_lesson";
import type { CreateChapterLessonResponse } from "./chapter_lesson";
import type { CreateChapterLessonRequest } from "./chapter_lesson";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { GetAllChapterLessonResponse } from "./chapter_lesson";
import type { GetAllChapterLessonRequest } from "./chapter_lesson";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service chapter_lesson.ChapterLessonService
 */
export interface IChapterLessonServiceClient {
    /**
     * @generated from protobuf rpc: GetAllChapterLesson
     */
    getAllChapterLesson(input: GetAllChapterLessonRequest, options?: RpcOptions): UnaryCall<GetAllChapterLessonRequest, GetAllChapterLessonResponse>;
    /**
     * @generated from protobuf rpc: CreateChapterLesson
     */
    createChapterLesson(input: CreateChapterLessonRequest, options?: RpcOptions): UnaryCall<CreateChapterLessonRequest, CreateChapterLessonResponse>;
    /**
     * @generated from protobuf rpc: DetailChapterLesson
     */
    detailChapterLesson(input: DetailChapterLessonRequest, options?: RpcOptions): UnaryCall<DetailChapterLessonRequest, DetailChapterLessonResponse>;
    /**
     * @generated from protobuf rpc: EditChapterLesson
     */
    editChapterLesson(input: EditChapterLessonRequest, options?: RpcOptions): UnaryCall<EditChapterLessonRequest, EditChapterLessonResponse>;
    /**
     * @generated from protobuf rpc: DeleteChapterLesson
     */
    deleteChapterLesson(input: DeleteChapterLessonRequest, options?: RpcOptions): UnaryCall<DeleteChapterLessonRequest, DeleteChapterLessonResponse>;
}
/**
 * @generated from protobuf service chapter_lesson.ChapterLessonService
 */
export class ChapterLessonServiceClient implements IChapterLessonServiceClient, ServiceInfo {
    typeName = ChapterLessonService.typeName;
    methods = ChapterLessonService.methods;
    options = ChapterLessonService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: GetAllChapterLesson
     */
    getAllChapterLesson(input: GetAllChapterLessonRequest, options?: RpcOptions): UnaryCall<GetAllChapterLessonRequest, GetAllChapterLessonResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetAllChapterLessonRequest, GetAllChapterLessonResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: CreateChapterLesson
     */
    createChapterLesson(input: CreateChapterLessonRequest, options?: RpcOptions): UnaryCall<CreateChapterLessonRequest, CreateChapterLessonResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<CreateChapterLessonRequest, CreateChapterLessonResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DetailChapterLesson
     */
    detailChapterLesson(input: DetailChapterLessonRequest, options?: RpcOptions): UnaryCall<DetailChapterLessonRequest, DetailChapterLessonResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<DetailChapterLessonRequest, DetailChapterLessonResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: EditChapterLesson
     */
    editChapterLesson(input: EditChapterLessonRequest, options?: RpcOptions): UnaryCall<EditChapterLessonRequest, EditChapterLessonResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<EditChapterLessonRequest, EditChapterLessonResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DeleteChapterLesson
     */
    deleteChapterLesson(input: DeleteChapterLessonRequest, options?: RpcOptions): UnaryCall<DeleteChapterLessonRequest, DeleteChapterLessonResponse> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeleteChapterLessonRequest, DeleteChapterLessonResponse>("unary", this._transport, method, opt, input);
    }
}
