// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "chapter_lesson/chapter_lesson.proto" (package "chapter_lesson", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { BaseResponse } from "../common/base_response";
import { FieldMask } from "../google/protobuf/field_mask";
/**
 * @generated from protobuf message chapter_lesson.GetAllChapterLessonRequest
 */
export interface GetAllChapterLessonRequest {
    /**
     * @generated from protobuf field: string chapter_id = 1
     */
    chapterId: string;
    /**
     * @generated from protobuf field: google.protobuf.FieldMask field_mask = 2
     */
    fieldMask?: FieldMask;
}
/**
 * @generated from protobuf message chapter_lesson.GetAllChapterLessonResponse
 */
export interface GetAllChapterLessonResponse {
    /**
     * @generated from protobuf field: common.BaseResponse base = 1
     */
    base?: BaseResponse;
    /**
     * @generated from protobuf field: repeated chapter_lesson.LessonInfo lessons = 2
     */
    lessons: LessonInfo[]; // 'repeated' untuk array/slice
}
/**
 * @generated from protobuf message chapter_lesson.LessonInfo
 */
export interface LessonInfo {
    /**
     * @generated from protobuf field: string id = 1
     */
    id: string;
    /**
     * @generated from protobuf field: optional string instructor_id = 2
     */
    instructorId?: string;
    /**
     * @generated from protobuf field: optional string course_id = 3
     */
    courseId?: string;
    /**
     * @generated from protobuf field: optional string chapter_id = 4
     */
    chapterId?: string;
    /**
     * @generated from protobuf field: optional string title = 5
     */
    title?: string;
    /**
     * @generated from protobuf field: optional int32 order_lesson = 6
     */
    orderLesson?: number;
    /**
     * @generated from protobuf field: optional string slug = 7
     */
    slug?: string;
    /**
     * @generated from protobuf field: optional string file_path = 8
     */
    filePath?: string;
    /**
     * @generated from protobuf field: optional string storage_lesson = 9
     */
    storageLesson?: string;
    /**
     * @generated from protobuf field: optional string lesson_type = 10
     */
    lessonType?: string;
    /**
     * @generated from protobuf field: optional string volume = 11
     */
    volume?: string;
    /**
     * @generated from protobuf field: optional string duration = 12
     */
    duration?: string;
    /**
     * @generated from protobuf field: optional string file_type = 13
     */
    fileType?: string;
    /**
     * @generated from protobuf field: optional string downloadable = 14
     */
    downloadable?: string;
    /**
     * @generated from protobuf field: optional int32 is_preview = 15
     */
    isPreview?: number;
    /**
     * @generated from protobuf field: optional string status = 16
     */
    status?: string;
    /**
     * @generated from protobuf field: optional string description = 17
     */
    description?: string;
}
/**
 * @generated from protobuf message chapter_lesson.CreateChapterLessonRequest
 */
export interface CreateChapterLessonRequest {
    /**
     * @generated from protobuf field: optional string instructor_id = 1
     */
    instructorId?: string;
    /**
     * @generated from protobuf field: optional string course_id = 2
     */
    courseId?: string;
    /**
     * @generated from protobuf field: optional string chapter_id = 3
     */
    chapterId?: string;
    /**
     * @generated from protobuf field: string title = 4
     */
    title: string;
    /**
     * @generated from protobuf field: int32 order_lesson = 5
     */
    orderLesson: number;
    /**
     * @generated from protobuf field: optional string slug = 6
     */
    slug?: string;
    /**
     * @generated from protobuf field: optional string description = 7
     */
    description?: string;
    /**
     * @generated from protobuf field: optional string file_path = 8
     */
    filePath?: string;
    /**
     * @generated from protobuf field: optional string storage_lesson = 9
     */
    storageLesson?: string;
    /**
     * @generated from protobuf field: optional string lesson_type = 10
     */
    lessonType?: string;
    /**
     * @generated from protobuf field: optional string volume = 11
     */
    volume?: string;
    /**
     * @generated from protobuf field: optional string duration = 12
     */
    duration?: string;
    /**
     * @generated from protobuf field: optional string file_type = 13
     */
    fileType?: string;
    /**
     * @generated from protobuf field: optional string downloadable = 14
     */
    downloadable?: string;
    /**
     * @generated from protobuf field: optional int32 is_preview = 15
     */
    isPreview?: number;
    /**
     * @generated from protobuf field: optional string status = 16
     */
    status?: string;
}
/**
 * @generated from protobuf message chapter_lesson.CreateChapterLessonResponse
 */
export interface CreateChapterLessonResponse {
    /**
     * @generated from protobuf field: common.BaseResponse base = 1
     */
    base?: BaseResponse;
    /**
     * @generated from protobuf field: string id = 2
     */
    id: string;
}
/**
 * @generated from protobuf message chapter_lesson.DetailChapterLessonRequest
 */
export interface DetailChapterLessonRequest {
    /**
     * @generated from protobuf field: string id = 1
     */
    id: string;
    /**
     * @generated from protobuf field: google.protobuf.FieldMask field_mask = 2
     */
    fieldMask?: FieldMask;
}
/**
 * @generated from protobuf message chapter_lesson.DetailChapterLessonResponse
 */
export interface DetailChapterLessonResponse {
    /**
     * @generated from protobuf field: common.BaseResponse base = 1
     */
    base?: BaseResponse;
    /**
     * @generated from protobuf field: string id = 2
     */
    id: string;
    /**
     * @generated from protobuf field: optional string chapter_id = 3
     */
    chapterId?: string;
    /**
     * @generated from protobuf field: string title = 4
     */
    title: string;
    /**
     * @generated from protobuf field: int32 order_lesson = 5
     */
    orderLesson: number;
    /**
     * @generated from protobuf field: optional string slug = 6
     */
    slug?: string;
    /**
     * @generated from protobuf field: optional string description = 7
     */
    description?: string;
    /**
     * @generated from protobuf field: optional string file_path = 8
     */
    filePath?: string;
    /**
     * @generated from protobuf field: optional string storage_lesson = 9
     */
    storageLesson?: string;
    /**
     * @generated from protobuf field: optional string lesson_type = 10
     */
    lessonType?: string;
    /**
     * @generated from protobuf field: optional string volume = 11
     */
    volume?: string;
    /**
     * @generated from protobuf field: optional string duration = 12
     */
    duration?: string;
    /**
     * @generated from protobuf field: optional string file_type = 13
     */
    fileType?: string;
    /**
     * @generated from protobuf field: optional string downloadable = 14
     */
    downloadable?: string;
    /**
     * @generated from protobuf field: optional int32 is_preview = 15
     */
    isPreview?: number;
    /**
     * @generated from protobuf field: optional string status = 16
     */
    status?: string;
    /**
     * @generated from protobuf field: optional string instructor_id = 17
     */
    instructorId?: string;
    /**
     * @generated from protobuf field: optional string course_id = 18
     */
    courseId?: string;
    /**
     * @generated from protobuf field: optional string created_at = 19
     */
    createdAt?: string;
    /**
     * @generated from protobuf field: optional string created_by = 20
     */
    createdBy?: string;
    /**
     * @generated from protobuf field: optional string deleted_by = 21
     */
    deletedBy?: string;
    /**
     * @generated from protobuf field: optional string updated_at = 22
     */
    updatedAt?: string;
    /**
     * @generated from protobuf field: optional string updated_by = 23
     */
    updatedBy?: string;
    /**
     * @generated from protobuf field: optional string deleted_at = 24
     */
    deletedAt?: string;
}
/**
 * @generated from protobuf message chapter_lesson.EditChapterLessonRequest
 */
export interface EditChapterLessonRequest {
    /**
     * @generated from protobuf field: string id = 1
     */
    id: string;
    /**
     * @generated from protobuf field: optional string course_id = 2
     */
    courseId?: string;
    /**
     * @generated from protobuf field: optional string chapter_id = 3
     */
    chapterId?: string;
    /**
     * @generated from protobuf field: string title = 4
     */
    title: string;
    /**
     * @generated from protobuf field: int32 order_lesson = 5
     */
    orderLesson: number;
    /**
     * @generated from protobuf field: optional string slug = 6
     */
    slug?: string;
    /**
     * @generated from protobuf field: optional string description = 7
     */
    description?: string;
    /**
     * @generated from protobuf field: optional string file_path = 8
     */
    filePath?: string;
    /**
     * @generated from protobuf field: optional string storage_lesson = 9
     */
    storageLesson?: string;
    /**
     * @generated from protobuf field: optional string lesson_type = 10
     */
    lessonType?: string;
    /**
     * @generated from protobuf field: optional string volume = 11
     */
    volume?: string;
    /**
     * @generated from protobuf field: optional string duration = 12
     */
    duration?: string;
    /**
     * @generated from protobuf field: optional string file_type = 13
     */
    fileType?: string;
    /**
     * @generated from protobuf field: optional string downloadable = 14
     */
    downloadable?: string;
    /**
     * @generated from protobuf field: optional int32 is_preview = 15
     */
    isPreview?: number;
    /**
     * @generated from protobuf field: optional string status = 16
     */
    status?: string;
    /**
     * @generated from protobuf field: optional string instructor_id = 17
     */
    instructorId?: string;
}
/**
 * @generated from protobuf message chapter_lesson.EditChapterLessonResponse
 */
export interface EditChapterLessonResponse {
    /**
     * @generated from protobuf field: common.BaseResponse base = 1
     */
    base?: BaseResponse;
    /**
     * @generated from protobuf field: string id = 2
     */
    id: string;
}
/**
 * @generated from protobuf message chapter_lesson.DeleteChapterLessonRequest
 */
export interface DeleteChapterLessonRequest {
    /**
     * @generated from protobuf field: string id = 1
     */
    id: string;
}
/**
 * @generated from protobuf message chapter_lesson.DeleteChapterLessonResponse
 */
export interface DeleteChapterLessonResponse {
    /**
     * @generated from protobuf field: common.BaseResponse base = 1
     */
    base?: BaseResponse;
}
// @generated message type with reflection information, may provide speed optimized methods
class GetAllChapterLessonRequest$Type extends MessageType<GetAllChapterLessonRequest> {
    constructor() {
        super("chapter_lesson.GetAllChapterLessonRequest", [
            { no: 1, name: "chapter_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "field_mask", kind: "message", T: () => FieldMask }
        ]);
    }
    create(value?: PartialMessage<GetAllChapterLessonRequest>): GetAllChapterLessonRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.chapterId = "";
        if (value !== undefined)
            reflectionMergePartial<GetAllChapterLessonRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetAllChapterLessonRequest): GetAllChapterLessonRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string chapter_id */ 1:
                    message.chapterId = reader.string();
                    break;
                case /* google.protobuf.FieldMask field_mask */ 2:
                    message.fieldMask = FieldMask.internalBinaryRead(reader, reader.uint32(), options, message.fieldMask);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetAllChapterLessonRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string chapter_id = 1; */
        if (message.chapterId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.chapterId);
        /* google.protobuf.FieldMask field_mask = 2; */
        if (message.fieldMask)
            FieldMask.internalBinaryWrite(message.fieldMask, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chapter_lesson.GetAllChapterLessonRequest
 */
export const GetAllChapterLessonRequest = new GetAllChapterLessonRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetAllChapterLessonResponse$Type extends MessageType<GetAllChapterLessonResponse> {
    constructor() {
        super("chapter_lesson.GetAllChapterLessonResponse", [
            { no: 1, name: "base", kind: "message", T: () => BaseResponse },
            { no: 2, name: "lessons", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => LessonInfo }
        ]);
    }
    create(value?: PartialMessage<GetAllChapterLessonResponse>): GetAllChapterLessonResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.lessons = [];
        if (value !== undefined)
            reflectionMergePartial<GetAllChapterLessonResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetAllChapterLessonResponse): GetAllChapterLessonResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* common.BaseResponse base */ 1:
                    message.base = BaseResponse.internalBinaryRead(reader, reader.uint32(), options, message.base);
                    break;
                case /* repeated chapter_lesson.LessonInfo lessons */ 2:
                    message.lessons.push(LessonInfo.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetAllChapterLessonResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* common.BaseResponse base = 1; */
        if (message.base)
            BaseResponse.internalBinaryWrite(message.base, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* repeated chapter_lesson.LessonInfo lessons = 2; */
        for (let i = 0; i < message.lessons.length; i++)
            LessonInfo.internalBinaryWrite(message.lessons[i], writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chapter_lesson.GetAllChapterLessonResponse
 */
export const GetAllChapterLessonResponse = new GetAllChapterLessonResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class LessonInfo$Type extends MessageType<LessonInfo> {
    constructor() {
        super("chapter_lesson.LessonInfo", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "instructor_id", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/, options: { "buf.validate.field": { string: { minLen: "1", maxLen: "255" } } } },
            { no: 3, name: "course_id", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/, options: { "buf.validate.field": { string: { minLen: "1", maxLen: "255" } } } },
            { no: 4, name: "chapter_id", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/, options: { "buf.validate.field": { string: { minLen: "1", maxLen: "255" } } } },
            { no: 5, name: "title", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/, options: { "buf.validate.field": { string: { minLen: "1", maxLen: "255" } } } },
            { no: 6, name: "order_lesson", kind: "scalar", opt: true, T: 5 /*ScalarType.INT32*/, options: { "buf.validate.field": { int32: { gte: 0 } } } },
            { no: 7, name: "slug", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/, options: { "buf.validate.field": { string: { maxLen: "255" } } } },
            { no: 8, name: "file_path", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/, options: { "buf.validate.field": { string: { maxLen: "255" } } } },
            { no: 9, name: "storage_lesson", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/, options: { "buf.validate.field": { string: { maxLen: "255" } } } },
            { no: 10, name: "lesson_type", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/, options: { "buf.validate.field": { string: { maxLen: "255" } } } },
            { no: 11, name: "volume", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/, options: { "buf.validate.field": { string: { maxLen: "255" } } } },
            { no: 12, name: "duration", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/, options: { "buf.validate.field": { string: { maxLen: "255" } } } },
            { no: 13, name: "file_type", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/, options: { "buf.validate.field": { string: { maxLen: "255" } } } },
            { no: 14, name: "downloadable", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/, options: { "buf.validate.field": { string: { maxLen: "255" } } } },
            { no: 15, name: "is_preview", kind: "scalar", opt: true, T: 5 /*ScalarType.INT32*/, options: { "buf.validate.field": { int32: { gte: 0 } } } },
            { no: 16, name: "status", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/, options: { "buf.validate.field": { string: { maxLen: "255" } } } },
            { no: 17, name: "description", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/, options: { "buf.validate.field": { string: { maxLen: "255" } } } }
        ]);
    }
    create(value?: PartialMessage<LessonInfo>): LessonInfo {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        if (value !== undefined)
            reflectionMergePartial<LessonInfo>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: LessonInfo): LessonInfo {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                case /* optional string instructor_id */ 2:
                    message.instructorId = reader.string();
                    break;
                case /* optional string course_id */ 3:
                    message.courseId = reader.string();
                    break;
                case /* optional string chapter_id */ 4:
                    message.chapterId = reader.string();
                    break;
                case /* optional string title */ 5:
                    message.title = reader.string();
                    break;
                case /* optional int32 order_lesson */ 6:
                    message.orderLesson = reader.int32();
                    break;
                case /* optional string slug */ 7:
                    message.slug = reader.string();
                    break;
                case /* optional string file_path */ 8:
                    message.filePath = reader.string();
                    break;
                case /* optional string storage_lesson */ 9:
                    message.storageLesson = reader.string();
                    break;
                case /* optional string lesson_type */ 10:
                    message.lessonType = reader.string();
                    break;
                case /* optional string volume */ 11:
                    message.volume = reader.string();
                    break;
                case /* optional string duration */ 12:
                    message.duration = reader.string();
                    break;
                case /* optional string file_type */ 13:
                    message.fileType = reader.string();
                    break;
                case /* optional string downloadable */ 14:
                    message.downloadable = reader.string();
                    break;
                case /* optional int32 is_preview */ 15:
                    message.isPreview = reader.int32();
                    break;
                case /* optional string status */ 16:
                    message.status = reader.string();
                    break;
                case /* optional string description */ 17:
                    message.description = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: LessonInfo, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        /* optional string instructor_id = 2; */
        if (message.instructorId !== undefined)
            writer.tag(2, WireType.LengthDelimited).string(message.instructorId);
        /* optional string course_id = 3; */
        if (message.courseId !== undefined)
            writer.tag(3, WireType.LengthDelimited).string(message.courseId);
        /* optional string chapter_id = 4; */
        if (message.chapterId !== undefined)
            writer.tag(4, WireType.LengthDelimited).string(message.chapterId);
        /* optional string title = 5; */
        if (message.title !== undefined)
            writer.tag(5, WireType.LengthDelimited).string(message.title);
        /* optional int32 order_lesson = 6; */
        if (message.orderLesson !== undefined)
            writer.tag(6, WireType.Varint).int32(message.orderLesson);
        /* optional string slug = 7; */
        if (message.slug !== undefined)
            writer.tag(7, WireType.LengthDelimited).string(message.slug);
        /* optional string file_path = 8; */
        if (message.filePath !== undefined)
            writer.tag(8, WireType.LengthDelimited).string(message.filePath);
        /* optional string storage_lesson = 9; */
        if (message.storageLesson !== undefined)
            writer.tag(9, WireType.LengthDelimited).string(message.storageLesson);
        /* optional string lesson_type = 10; */
        if (message.lessonType !== undefined)
            writer.tag(10, WireType.LengthDelimited).string(message.lessonType);
        /* optional string volume = 11; */
        if (message.volume !== undefined)
            writer.tag(11, WireType.LengthDelimited).string(message.volume);
        /* optional string duration = 12; */
        if (message.duration !== undefined)
            writer.tag(12, WireType.LengthDelimited).string(message.duration);
        /* optional string file_type = 13; */
        if (message.fileType !== undefined)
            writer.tag(13, WireType.LengthDelimited).string(message.fileType);
        /* optional string downloadable = 14; */
        if (message.downloadable !== undefined)
            writer.tag(14, WireType.LengthDelimited).string(message.downloadable);
        /* optional int32 is_preview = 15; */
        if (message.isPreview !== undefined)
            writer.tag(15, WireType.Varint).int32(message.isPreview);
        /* optional string status = 16; */
        if (message.status !== undefined)
            writer.tag(16, WireType.LengthDelimited).string(message.status);
        /* optional string description = 17; */
        if (message.description !== undefined)
            writer.tag(17, WireType.LengthDelimited).string(message.description);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chapter_lesson.LessonInfo
 */
export const LessonInfo = new LessonInfo$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CreateChapterLessonRequest$Type extends MessageType<CreateChapterLessonRequest> {
    constructor() {
        super("chapter_lesson.CreateChapterLessonRequest", [
            { no: 1, name: "instructor_id", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/, options: { "buf.validate.field": { string: { minLen: "1", maxLen: "255" } } } },
            { no: 2, name: "course_id", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/, options: { "buf.validate.field": { string: { minLen: "1", maxLen: "255" } } } },
            { no: 3, name: "chapter_id", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/, options: { "buf.validate.field": { string: { minLen: "1", maxLen: "255" } } } },
            { no: 4, name: "title", kind: "scalar", T: 9 /*ScalarType.STRING*/, options: { "buf.validate.field": { string: { minLen: "1", maxLen: "255" } } } },
            { no: 5, name: "order_lesson", kind: "scalar", T: 5 /*ScalarType.INT32*/, options: { "buf.validate.field": { int32: { gte: 0 } } } },
            { no: 6, name: "slug", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/, options: { "buf.validate.field": { string: { maxLen: "255" } } } },
            { no: 7, name: "description", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/, options: { "buf.validate.field": { string: { maxLen: "255" } } } },
            { no: 8, name: "file_path", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/, options: { "buf.validate.field": { string: { maxLen: "255" } } } },
            { no: 9, name: "storage_lesson", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/, options: { "buf.validate.field": { string: { maxLen: "255" } } } },
            { no: 10, name: "lesson_type", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/, options: { "buf.validate.field": { string: { maxLen: "255" } } } },
            { no: 11, name: "volume", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/, options: { "buf.validate.field": { string: { maxLen: "255" } } } },
            { no: 12, name: "duration", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/, options: { "buf.validate.field": { string: { maxLen: "255" } } } },
            { no: 13, name: "file_type", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/, options: { "buf.validate.field": { string: { maxLen: "255" } } } },
            { no: 14, name: "downloadable", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/, options: { "buf.validate.field": { string: { maxLen: "255" } } } },
            { no: 15, name: "is_preview", kind: "scalar", opt: true, T: 5 /*ScalarType.INT32*/, options: { "buf.validate.field": { int32: { gte: 0 } } } },
            { no: 16, name: "status", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/, options: { "buf.validate.field": { string: { maxLen: "255" } } } }
        ]);
    }
    create(value?: PartialMessage<CreateChapterLessonRequest>): CreateChapterLessonRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.title = "";
        message.orderLesson = 0;
        if (value !== undefined)
            reflectionMergePartial<CreateChapterLessonRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CreateChapterLessonRequest): CreateChapterLessonRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* optional string instructor_id */ 1:
                    message.instructorId = reader.string();
                    break;
                case /* optional string course_id */ 2:
                    message.courseId = reader.string();
                    break;
                case /* optional string chapter_id */ 3:
                    message.chapterId = reader.string();
                    break;
                case /* string title */ 4:
                    message.title = reader.string();
                    break;
                case /* int32 order_lesson */ 5:
                    message.orderLesson = reader.int32();
                    break;
                case /* optional string slug */ 6:
                    message.slug = reader.string();
                    break;
                case /* optional string description */ 7:
                    message.description = reader.string();
                    break;
                case /* optional string file_path */ 8:
                    message.filePath = reader.string();
                    break;
                case /* optional string storage_lesson */ 9:
                    message.storageLesson = reader.string();
                    break;
                case /* optional string lesson_type */ 10:
                    message.lessonType = reader.string();
                    break;
                case /* optional string volume */ 11:
                    message.volume = reader.string();
                    break;
                case /* optional string duration */ 12:
                    message.duration = reader.string();
                    break;
                case /* optional string file_type */ 13:
                    message.fileType = reader.string();
                    break;
                case /* optional string downloadable */ 14:
                    message.downloadable = reader.string();
                    break;
                case /* optional int32 is_preview */ 15:
                    message.isPreview = reader.int32();
                    break;
                case /* optional string status */ 16:
                    message.status = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CreateChapterLessonRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* optional string instructor_id = 1; */
        if (message.instructorId !== undefined)
            writer.tag(1, WireType.LengthDelimited).string(message.instructorId);
        /* optional string course_id = 2; */
        if (message.courseId !== undefined)
            writer.tag(2, WireType.LengthDelimited).string(message.courseId);
        /* optional string chapter_id = 3; */
        if (message.chapterId !== undefined)
            writer.tag(3, WireType.LengthDelimited).string(message.chapterId);
        /* string title = 4; */
        if (message.title !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.title);
        /* int32 order_lesson = 5; */
        if (message.orderLesson !== 0)
            writer.tag(5, WireType.Varint).int32(message.orderLesson);
        /* optional string slug = 6; */
        if (message.slug !== undefined)
            writer.tag(6, WireType.LengthDelimited).string(message.slug);
        /* optional string description = 7; */
        if (message.description !== undefined)
            writer.tag(7, WireType.LengthDelimited).string(message.description);
        /* optional string file_path = 8; */
        if (message.filePath !== undefined)
            writer.tag(8, WireType.LengthDelimited).string(message.filePath);
        /* optional string storage_lesson = 9; */
        if (message.storageLesson !== undefined)
            writer.tag(9, WireType.LengthDelimited).string(message.storageLesson);
        /* optional string lesson_type = 10; */
        if (message.lessonType !== undefined)
            writer.tag(10, WireType.LengthDelimited).string(message.lessonType);
        /* optional string volume = 11; */
        if (message.volume !== undefined)
            writer.tag(11, WireType.LengthDelimited).string(message.volume);
        /* optional string duration = 12; */
        if (message.duration !== undefined)
            writer.tag(12, WireType.LengthDelimited).string(message.duration);
        /* optional string file_type = 13; */
        if (message.fileType !== undefined)
            writer.tag(13, WireType.LengthDelimited).string(message.fileType);
        /* optional string downloadable = 14; */
        if (message.downloadable !== undefined)
            writer.tag(14, WireType.LengthDelimited).string(message.downloadable);
        /* optional int32 is_preview = 15; */
        if (message.isPreview !== undefined)
            writer.tag(15, WireType.Varint).int32(message.isPreview);
        /* optional string status = 16; */
        if (message.status !== undefined)
            writer.tag(16, WireType.LengthDelimited).string(message.status);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chapter_lesson.CreateChapterLessonRequest
 */
export const CreateChapterLessonRequest = new CreateChapterLessonRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CreateChapterLessonResponse$Type extends MessageType<CreateChapterLessonResponse> {
    constructor() {
        super("chapter_lesson.CreateChapterLessonResponse", [
            { no: 1, name: "base", kind: "message", T: () => BaseResponse },
            { no: 2, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<CreateChapterLessonResponse>): CreateChapterLessonResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        if (value !== undefined)
            reflectionMergePartial<CreateChapterLessonResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CreateChapterLessonResponse): CreateChapterLessonResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* common.BaseResponse base */ 1:
                    message.base = BaseResponse.internalBinaryRead(reader, reader.uint32(), options, message.base);
                    break;
                case /* string id */ 2:
                    message.id = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CreateChapterLessonResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* common.BaseResponse base = 1; */
        if (message.base)
            BaseResponse.internalBinaryWrite(message.base, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* string id = 2; */
        if (message.id !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.id);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chapter_lesson.CreateChapterLessonResponse
 */
export const CreateChapterLessonResponse = new CreateChapterLessonResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DetailChapterLessonRequest$Type extends MessageType<DetailChapterLessonRequest> {
    constructor() {
        super("chapter_lesson.DetailChapterLessonRequest", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/, options: { "buf.validate.field": { string: { minLen: "1", maxLen: "255" } } } },
            { no: 2, name: "field_mask", kind: "message", T: () => FieldMask }
        ]);
    }
    create(value?: PartialMessage<DetailChapterLessonRequest>): DetailChapterLessonRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        if (value !== undefined)
            reflectionMergePartial<DetailChapterLessonRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DetailChapterLessonRequest): DetailChapterLessonRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                case /* google.protobuf.FieldMask field_mask */ 2:
                    message.fieldMask = FieldMask.internalBinaryRead(reader, reader.uint32(), options, message.fieldMask);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: DetailChapterLessonRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        /* google.protobuf.FieldMask field_mask = 2; */
        if (message.fieldMask)
            FieldMask.internalBinaryWrite(message.fieldMask, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chapter_lesson.DetailChapterLessonRequest
 */
export const DetailChapterLessonRequest = new DetailChapterLessonRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DetailChapterLessonResponse$Type extends MessageType<DetailChapterLessonResponse> {
    constructor() {
        super("chapter_lesson.DetailChapterLessonResponse", [
            { no: 1, name: "base", kind: "message", T: () => BaseResponse },
            { no: 2, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "chapter_id", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/, options: { "buf.validate.field": { string: { minLen: "1", maxLen: "255" } } } },
            { no: 4, name: "title", kind: "scalar", T: 9 /*ScalarType.STRING*/, options: { "buf.validate.field": { string: { minLen: "1", maxLen: "255" } } } },
            { no: 5, name: "order_lesson", kind: "scalar", T: 5 /*ScalarType.INT32*/, options: { "buf.validate.field": { int32: { gte: 0 } } } },
            { no: 6, name: "slug", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/, options: { "buf.validate.field": { string: { maxLen: "255" } } } },
            { no: 7, name: "description", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/, options: { "buf.validate.field": { string: { maxLen: "255" } } } },
            { no: 8, name: "file_path", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/, options: { "buf.validate.field": { string: { maxLen: "255" } } } },
            { no: 9, name: "storage_lesson", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/, options: { "buf.validate.field": { string: { maxLen: "255" } } } },
            { no: 10, name: "lesson_type", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/, options: { "buf.validate.field": { string: { maxLen: "255" } } } },
            { no: 11, name: "volume", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/, options: { "buf.validate.field": { string: { maxLen: "255" } } } },
            { no: 12, name: "duration", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/, options: { "buf.validate.field": { string: { maxLen: "255" } } } },
            { no: 13, name: "file_type", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/, options: { "buf.validate.field": { string: { maxLen: "255" } } } },
            { no: 14, name: "downloadable", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/, options: { "buf.validate.field": { string: { maxLen: "255" } } } },
            { no: 15, name: "is_preview", kind: "scalar", opt: true, T: 5 /*ScalarType.INT32*/, options: { "buf.validate.field": { int32: { gte: 0 } } } },
            { no: 16, name: "status", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/, options: { "buf.validate.field": { string: { maxLen: "255" } } } },
            { no: 17, name: "instructor_id", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/, options: { "buf.validate.field": { string: { minLen: "1", maxLen: "255" } } } },
            { no: 18, name: "course_id", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/, options: { "buf.validate.field": { string: { minLen: "1", maxLen: "255" } } } },
            { no: 19, name: "created_at", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 20, name: "created_by", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 21, name: "deleted_by", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 22, name: "updated_at", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 23, name: "updated_by", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 24, name: "deleted_at", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<DetailChapterLessonResponse>): DetailChapterLessonResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        message.title = "";
        message.orderLesson = 0;
        if (value !== undefined)
            reflectionMergePartial<DetailChapterLessonResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DetailChapterLessonResponse): DetailChapterLessonResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* common.BaseResponse base */ 1:
                    message.base = BaseResponse.internalBinaryRead(reader, reader.uint32(), options, message.base);
                    break;
                case /* string id */ 2:
                    message.id = reader.string();
                    break;
                case /* optional string chapter_id */ 3:
                    message.chapterId = reader.string();
                    break;
                case /* string title */ 4:
                    message.title = reader.string();
                    break;
                case /* int32 order_lesson */ 5:
                    message.orderLesson = reader.int32();
                    break;
                case /* optional string slug */ 6:
                    message.slug = reader.string();
                    break;
                case /* optional string description */ 7:
                    message.description = reader.string();
                    break;
                case /* optional string file_path */ 8:
                    message.filePath = reader.string();
                    break;
                case /* optional string storage_lesson */ 9:
                    message.storageLesson = reader.string();
                    break;
                case /* optional string lesson_type */ 10:
                    message.lessonType = reader.string();
                    break;
                case /* optional string volume */ 11:
                    message.volume = reader.string();
                    break;
                case /* optional string duration */ 12:
                    message.duration = reader.string();
                    break;
                case /* optional string file_type */ 13:
                    message.fileType = reader.string();
                    break;
                case /* optional string downloadable */ 14:
                    message.downloadable = reader.string();
                    break;
                case /* optional int32 is_preview */ 15:
                    message.isPreview = reader.int32();
                    break;
                case /* optional string status */ 16:
                    message.status = reader.string();
                    break;
                case /* optional string instructor_id */ 17:
                    message.instructorId = reader.string();
                    break;
                case /* optional string course_id */ 18:
                    message.courseId = reader.string();
                    break;
                case /* optional string created_at */ 19:
                    message.createdAt = reader.string();
                    break;
                case /* optional string created_by */ 20:
                    message.createdBy = reader.string();
                    break;
                case /* optional string deleted_by */ 21:
                    message.deletedBy = reader.string();
                    break;
                case /* optional string updated_at */ 22:
                    message.updatedAt = reader.string();
                    break;
                case /* optional string updated_by */ 23:
                    message.updatedBy = reader.string();
                    break;
                case /* optional string deleted_at */ 24:
                    message.deletedAt = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: DetailChapterLessonResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* common.BaseResponse base = 1; */
        if (message.base)
            BaseResponse.internalBinaryWrite(message.base, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* string id = 2; */
        if (message.id !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.id);
        /* optional string chapter_id = 3; */
        if (message.chapterId !== undefined)
            writer.tag(3, WireType.LengthDelimited).string(message.chapterId);
        /* string title = 4; */
        if (message.title !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.title);
        /* int32 order_lesson = 5; */
        if (message.orderLesson !== 0)
            writer.tag(5, WireType.Varint).int32(message.orderLesson);
        /* optional string slug = 6; */
        if (message.slug !== undefined)
            writer.tag(6, WireType.LengthDelimited).string(message.slug);
        /* optional string description = 7; */
        if (message.description !== undefined)
            writer.tag(7, WireType.LengthDelimited).string(message.description);
        /* optional string file_path = 8; */
        if (message.filePath !== undefined)
            writer.tag(8, WireType.LengthDelimited).string(message.filePath);
        /* optional string storage_lesson = 9; */
        if (message.storageLesson !== undefined)
            writer.tag(9, WireType.LengthDelimited).string(message.storageLesson);
        /* optional string lesson_type = 10; */
        if (message.lessonType !== undefined)
            writer.tag(10, WireType.LengthDelimited).string(message.lessonType);
        /* optional string volume = 11; */
        if (message.volume !== undefined)
            writer.tag(11, WireType.LengthDelimited).string(message.volume);
        /* optional string duration = 12; */
        if (message.duration !== undefined)
            writer.tag(12, WireType.LengthDelimited).string(message.duration);
        /* optional string file_type = 13; */
        if (message.fileType !== undefined)
            writer.tag(13, WireType.LengthDelimited).string(message.fileType);
        /* optional string downloadable = 14; */
        if (message.downloadable !== undefined)
            writer.tag(14, WireType.LengthDelimited).string(message.downloadable);
        /* optional int32 is_preview = 15; */
        if (message.isPreview !== undefined)
            writer.tag(15, WireType.Varint).int32(message.isPreview);
        /* optional string status = 16; */
        if (message.status !== undefined)
            writer.tag(16, WireType.LengthDelimited).string(message.status);
        /* optional string instructor_id = 17; */
        if (message.instructorId !== undefined)
            writer.tag(17, WireType.LengthDelimited).string(message.instructorId);
        /* optional string course_id = 18; */
        if (message.courseId !== undefined)
            writer.tag(18, WireType.LengthDelimited).string(message.courseId);
        /* optional string created_at = 19; */
        if (message.createdAt !== undefined)
            writer.tag(19, WireType.LengthDelimited).string(message.createdAt);
        /* optional string created_by = 20; */
        if (message.createdBy !== undefined)
            writer.tag(20, WireType.LengthDelimited).string(message.createdBy);
        /* optional string deleted_by = 21; */
        if (message.deletedBy !== undefined)
            writer.tag(21, WireType.LengthDelimited).string(message.deletedBy);
        /* optional string updated_at = 22; */
        if (message.updatedAt !== undefined)
            writer.tag(22, WireType.LengthDelimited).string(message.updatedAt);
        /* optional string updated_by = 23; */
        if (message.updatedBy !== undefined)
            writer.tag(23, WireType.LengthDelimited).string(message.updatedBy);
        /* optional string deleted_at = 24; */
        if (message.deletedAt !== undefined)
            writer.tag(24, WireType.LengthDelimited).string(message.deletedAt);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chapter_lesson.DetailChapterLessonResponse
 */
export const DetailChapterLessonResponse = new DetailChapterLessonResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class EditChapterLessonRequest$Type extends MessageType<EditChapterLessonRequest> {
    constructor() {
        super("chapter_lesson.EditChapterLessonRequest", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/, options: { "buf.validate.field": { string: { minLen: "1", maxLen: "255" } } } },
            { no: 2, name: "course_id", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/, options: { "buf.validate.field": { string: { minLen: "1", maxLen: "255" } } } },
            { no: 3, name: "chapter_id", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/, options: { "buf.validate.field": { string: { minLen: "1", maxLen: "255" } } } },
            { no: 4, name: "title", kind: "scalar", T: 9 /*ScalarType.STRING*/, options: { "buf.validate.field": { string: { minLen: "1", maxLen: "255" } } } },
            { no: 5, name: "order_lesson", kind: "scalar", T: 5 /*ScalarType.INT32*/, options: { "buf.validate.field": { int32: { gte: 0 } } } },
            { no: 6, name: "slug", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/, options: { "buf.validate.field": { string: { maxLen: "255" } } } },
            { no: 7, name: "description", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/, options: { "buf.validate.field": { string: { maxLen: "255" } } } },
            { no: 8, name: "file_path", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/, options: { "buf.validate.field": { string: { maxLen: "255" } } } },
            { no: 9, name: "storage_lesson", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/, options: { "buf.validate.field": { string: { maxLen: "255" } } } },
            { no: 10, name: "lesson_type", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/, options: { "buf.validate.field": { string: { maxLen: "255" } } } },
            { no: 11, name: "volume", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/, options: { "buf.validate.field": { string: { maxLen: "255" } } } },
            { no: 12, name: "duration", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/, options: { "buf.validate.field": { string: { maxLen: "255" } } } },
            { no: 13, name: "file_type", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/, options: { "buf.validate.field": { string: { maxLen: "255" } } } },
            { no: 14, name: "downloadable", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/, options: { "buf.validate.field": { string: { maxLen: "255" } } } },
            { no: 15, name: "is_preview", kind: "scalar", opt: true, T: 5 /*ScalarType.INT32*/, options: { "buf.validate.field": { int32: { gte: 0 } } } },
            { no: 16, name: "status", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/, options: { "buf.validate.field": { string: { maxLen: "255" } } } },
            { no: 17, name: "instructor_id", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/, options: { "buf.validate.field": { string: { minLen: "1", maxLen: "255" } } } }
        ]);
    }
    create(value?: PartialMessage<EditChapterLessonRequest>): EditChapterLessonRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        message.title = "";
        message.orderLesson = 0;
        if (value !== undefined)
            reflectionMergePartial<EditChapterLessonRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: EditChapterLessonRequest): EditChapterLessonRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                case /* optional string course_id */ 2:
                    message.courseId = reader.string();
                    break;
                case /* optional string chapter_id */ 3:
                    message.chapterId = reader.string();
                    break;
                case /* string title */ 4:
                    message.title = reader.string();
                    break;
                case /* int32 order_lesson */ 5:
                    message.orderLesson = reader.int32();
                    break;
                case /* optional string slug */ 6:
                    message.slug = reader.string();
                    break;
                case /* optional string description */ 7:
                    message.description = reader.string();
                    break;
                case /* optional string file_path */ 8:
                    message.filePath = reader.string();
                    break;
                case /* optional string storage_lesson */ 9:
                    message.storageLesson = reader.string();
                    break;
                case /* optional string lesson_type */ 10:
                    message.lessonType = reader.string();
                    break;
                case /* optional string volume */ 11:
                    message.volume = reader.string();
                    break;
                case /* optional string duration */ 12:
                    message.duration = reader.string();
                    break;
                case /* optional string file_type */ 13:
                    message.fileType = reader.string();
                    break;
                case /* optional string downloadable */ 14:
                    message.downloadable = reader.string();
                    break;
                case /* optional int32 is_preview */ 15:
                    message.isPreview = reader.int32();
                    break;
                case /* optional string status */ 16:
                    message.status = reader.string();
                    break;
                case /* optional string instructor_id */ 17:
                    message.instructorId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: EditChapterLessonRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        /* optional string course_id = 2; */
        if (message.courseId !== undefined)
            writer.tag(2, WireType.LengthDelimited).string(message.courseId);
        /* optional string chapter_id = 3; */
        if (message.chapterId !== undefined)
            writer.tag(3, WireType.LengthDelimited).string(message.chapterId);
        /* string title = 4; */
        if (message.title !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.title);
        /* int32 order_lesson = 5; */
        if (message.orderLesson !== 0)
            writer.tag(5, WireType.Varint).int32(message.orderLesson);
        /* optional string slug = 6; */
        if (message.slug !== undefined)
            writer.tag(6, WireType.LengthDelimited).string(message.slug);
        /* optional string description = 7; */
        if (message.description !== undefined)
            writer.tag(7, WireType.LengthDelimited).string(message.description);
        /* optional string file_path = 8; */
        if (message.filePath !== undefined)
            writer.tag(8, WireType.LengthDelimited).string(message.filePath);
        /* optional string storage_lesson = 9; */
        if (message.storageLesson !== undefined)
            writer.tag(9, WireType.LengthDelimited).string(message.storageLesson);
        /* optional string lesson_type = 10; */
        if (message.lessonType !== undefined)
            writer.tag(10, WireType.LengthDelimited).string(message.lessonType);
        /* optional string volume = 11; */
        if (message.volume !== undefined)
            writer.tag(11, WireType.LengthDelimited).string(message.volume);
        /* optional string duration = 12; */
        if (message.duration !== undefined)
            writer.tag(12, WireType.LengthDelimited).string(message.duration);
        /* optional string file_type = 13; */
        if (message.fileType !== undefined)
            writer.tag(13, WireType.LengthDelimited).string(message.fileType);
        /* optional string downloadable = 14; */
        if (message.downloadable !== undefined)
            writer.tag(14, WireType.LengthDelimited).string(message.downloadable);
        /* optional int32 is_preview = 15; */
        if (message.isPreview !== undefined)
            writer.tag(15, WireType.Varint).int32(message.isPreview);
        /* optional string status = 16; */
        if (message.status !== undefined)
            writer.tag(16, WireType.LengthDelimited).string(message.status);
        /* optional string instructor_id = 17; */
        if (message.instructorId !== undefined)
            writer.tag(17, WireType.LengthDelimited).string(message.instructorId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chapter_lesson.EditChapterLessonRequest
 */
export const EditChapterLessonRequest = new EditChapterLessonRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class EditChapterLessonResponse$Type extends MessageType<EditChapterLessonResponse> {
    constructor() {
        super("chapter_lesson.EditChapterLessonResponse", [
            { no: 1, name: "base", kind: "message", T: () => BaseResponse },
            { no: 2, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<EditChapterLessonResponse>): EditChapterLessonResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        if (value !== undefined)
            reflectionMergePartial<EditChapterLessonResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: EditChapterLessonResponse): EditChapterLessonResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* common.BaseResponse base */ 1:
                    message.base = BaseResponse.internalBinaryRead(reader, reader.uint32(), options, message.base);
                    break;
                case /* string id */ 2:
                    message.id = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: EditChapterLessonResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* common.BaseResponse base = 1; */
        if (message.base)
            BaseResponse.internalBinaryWrite(message.base, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* string id = 2; */
        if (message.id !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.id);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chapter_lesson.EditChapterLessonResponse
 */
export const EditChapterLessonResponse = new EditChapterLessonResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DeleteChapterLessonRequest$Type extends MessageType<DeleteChapterLessonRequest> {
    constructor() {
        super("chapter_lesson.DeleteChapterLessonRequest", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/, options: { "buf.validate.field": { string: { minLen: "1", maxLen: "255" } } } }
        ]);
    }
    create(value?: PartialMessage<DeleteChapterLessonRequest>): DeleteChapterLessonRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        if (value !== undefined)
            reflectionMergePartial<DeleteChapterLessonRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DeleteChapterLessonRequest): DeleteChapterLessonRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: DeleteChapterLessonRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chapter_lesson.DeleteChapterLessonRequest
 */
export const DeleteChapterLessonRequest = new DeleteChapterLessonRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DeleteChapterLessonResponse$Type extends MessageType<DeleteChapterLessonResponse> {
    constructor() {
        super("chapter_lesson.DeleteChapterLessonResponse", [
            { no: 1, name: "base", kind: "message", T: () => BaseResponse }
        ]);
    }
    create(value?: PartialMessage<DeleteChapterLessonResponse>): DeleteChapterLessonResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<DeleteChapterLessonResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DeleteChapterLessonResponse): DeleteChapterLessonResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* common.BaseResponse base */ 1:
                    message.base = BaseResponse.internalBinaryRead(reader, reader.uint32(), options, message.base);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: DeleteChapterLessonResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* common.BaseResponse base = 1; */
        if (message.base)
            BaseResponse.internalBinaryWrite(message.base, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chapter_lesson.DeleteChapterLessonResponse
 */
export const DeleteChapterLessonResponse = new DeleteChapterLessonResponse$Type();
/**
 * @generated ServiceType for protobuf service chapter_lesson.ChapterLessonService
 */
export const ChapterLessonService = new ServiceType("chapter_lesson.ChapterLessonService", [
    { name: "GetAllChapterLesson", options: {}, I: GetAllChapterLessonRequest, O: GetAllChapterLessonResponse },
    { name: "CreateChapterLesson", options: {}, I: CreateChapterLessonRequest, O: CreateChapterLessonResponse },
    { name: "DetailChapterLesson", options: {}, I: DetailChapterLessonRequest, O: DetailChapterLessonResponse },
    { name: "EditChapterLesson", options: {}, I: EditChapterLessonRequest, O: EditChapterLessonResponse },
    { name: "DeleteChapterLesson", options: {}, I: DeleteChapterLessonRequest, O: DeleteChapterLessonResponse }
]);
