// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: chapter_lesson/chapter_lesson.proto

package chapter_lesson

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ChapterLessonService_GetAllChapterLesson_FullMethodName = "/chapter_lesson.ChapterLessonService/GetAllChapterLesson"
	ChapterLessonService_CreateChapterLesson_FullMethodName = "/chapter_lesson.ChapterLessonService/CreateChapterLesson"
	ChapterLessonService_DetailChapterLesson_FullMethodName = "/chapter_lesson.ChapterLessonService/DetailChapterLesson"
	ChapterLessonService_EditChapterLesson_FullMethodName   = "/chapter_lesson.ChapterLessonService/EditChapterLesson"
	ChapterLessonService_DeleteChapterLesson_FullMethodName = "/chapter_lesson.ChapterLessonService/DeleteChapterLesson"
)

// ChapterLessonServiceClient is the client API for ChapterLessonService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChapterLessonServiceClient interface {
	GetAllChapterLesson(ctx context.Context, in *GetAllChapterLessonRequest, opts ...grpc.CallOption) (*GetAllChapterLessonResponse, error)
	CreateChapterLesson(ctx context.Context, in *CreateChapterLessonRequest, opts ...grpc.CallOption) (*CreateChapterLessonResponse, error)
	DetailChapterLesson(ctx context.Context, in *DetailChapterLessonRequest, opts ...grpc.CallOption) (*DetailChapterLessonResponse, error)
	EditChapterLesson(ctx context.Context, in *EditChapterLessonRequest, opts ...grpc.CallOption) (*EditChapterLessonResponse, error)
	DeleteChapterLesson(ctx context.Context, in *DeleteChapterLessonRequest, opts ...grpc.CallOption) (*DeleteChapterLessonResponse, error)
}

type chapterLessonServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChapterLessonServiceClient(cc grpc.ClientConnInterface) ChapterLessonServiceClient {
	return &chapterLessonServiceClient{cc}
}

func (c *chapterLessonServiceClient) GetAllChapterLesson(ctx context.Context, in *GetAllChapterLessonRequest, opts ...grpc.CallOption) (*GetAllChapterLessonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllChapterLessonResponse)
	err := c.cc.Invoke(ctx, ChapterLessonService_GetAllChapterLesson_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chapterLessonServiceClient) CreateChapterLesson(ctx context.Context, in *CreateChapterLessonRequest, opts ...grpc.CallOption) (*CreateChapterLessonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateChapterLessonResponse)
	err := c.cc.Invoke(ctx, ChapterLessonService_CreateChapterLesson_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chapterLessonServiceClient) DetailChapterLesson(ctx context.Context, in *DetailChapterLessonRequest, opts ...grpc.CallOption) (*DetailChapterLessonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DetailChapterLessonResponse)
	err := c.cc.Invoke(ctx, ChapterLessonService_DetailChapterLesson_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chapterLessonServiceClient) EditChapterLesson(ctx context.Context, in *EditChapterLessonRequest, opts ...grpc.CallOption) (*EditChapterLessonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EditChapterLessonResponse)
	err := c.cc.Invoke(ctx, ChapterLessonService_EditChapterLesson_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chapterLessonServiceClient) DeleteChapterLesson(ctx context.Context, in *DeleteChapterLessonRequest, opts ...grpc.CallOption) (*DeleteChapterLessonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteChapterLessonResponse)
	err := c.cc.Invoke(ctx, ChapterLessonService_DeleteChapterLesson_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChapterLessonServiceServer is the server API for ChapterLessonService service.
// All implementations must embed UnimplementedChapterLessonServiceServer
// for forward compatibility.
type ChapterLessonServiceServer interface {
	GetAllChapterLesson(context.Context, *GetAllChapterLessonRequest) (*GetAllChapterLessonResponse, error)
	CreateChapterLesson(context.Context, *CreateChapterLessonRequest) (*CreateChapterLessonResponse, error)
	DetailChapterLesson(context.Context, *DetailChapterLessonRequest) (*DetailChapterLessonResponse, error)
	EditChapterLesson(context.Context, *EditChapterLessonRequest) (*EditChapterLessonResponse, error)
	DeleteChapterLesson(context.Context, *DeleteChapterLessonRequest) (*DeleteChapterLessonResponse, error)
	mustEmbedUnimplementedChapterLessonServiceServer()
}

// UnimplementedChapterLessonServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChapterLessonServiceServer struct{}

func (UnimplementedChapterLessonServiceServer) GetAllChapterLesson(context.Context, *GetAllChapterLessonRequest) (*GetAllChapterLessonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllChapterLesson not implemented")
}
func (UnimplementedChapterLessonServiceServer) CreateChapterLesson(context.Context, *CreateChapterLessonRequest) (*CreateChapterLessonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateChapterLesson not implemented")
}
func (UnimplementedChapterLessonServiceServer) DetailChapterLesson(context.Context, *DetailChapterLessonRequest) (*DetailChapterLessonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DetailChapterLesson not implemented")
}
func (UnimplementedChapterLessonServiceServer) EditChapterLesson(context.Context, *EditChapterLessonRequest) (*EditChapterLessonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditChapterLesson not implemented")
}
func (UnimplementedChapterLessonServiceServer) DeleteChapterLesson(context.Context, *DeleteChapterLessonRequest) (*DeleteChapterLessonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteChapterLesson not implemented")
}
func (UnimplementedChapterLessonServiceServer) mustEmbedUnimplementedChapterLessonServiceServer() {}
func (UnimplementedChapterLessonServiceServer) testEmbeddedByValue()                              {}

// UnsafeChapterLessonServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChapterLessonServiceServer will
// result in compilation errors.
type UnsafeChapterLessonServiceServer interface {
	mustEmbedUnimplementedChapterLessonServiceServer()
}

func RegisterChapterLessonServiceServer(s grpc.ServiceRegistrar, srv ChapterLessonServiceServer) {
	// If the following call pancis, it indicates UnimplementedChapterLessonServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChapterLessonService_ServiceDesc, srv)
}

func _ChapterLessonService_GetAllChapterLesson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllChapterLessonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChapterLessonServiceServer).GetAllChapterLesson(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChapterLessonService_GetAllChapterLesson_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChapterLessonServiceServer).GetAllChapterLesson(ctx, req.(*GetAllChapterLessonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChapterLessonService_CreateChapterLesson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateChapterLessonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChapterLessonServiceServer).CreateChapterLesson(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChapterLessonService_CreateChapterLesson_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChapterLessonServiceServer).CreateChapterLesson(ctx, req.(*CreateChapterLessonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChapterLessonService_DetailChapterLesson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetailChapterLessonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChapterLessonServiceServer).DetailChapterLesson(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChapterLessonService_DetailChapterLesson_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChapterLessonServiceServer).DetailChapterLesson(ctx, req.(*DetailChapterLessonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChapterLessonService_EditChapterLesson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditChapterLessonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChapterLessonServiceServer).EditChapterLesson(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChapterLessonService_EditChapterLesson_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChapterLessonServiceServer).EditChapterLesson(ctx, req.(*EditChapterLessonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChapterLessonService_DeleteChapterLesson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteChapterLessonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChapterLessonServiceServer).DeleteChapterLesson(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChapterLessonService_DeleteChapterLesson_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChapterLessonServiceServer).DeleteChapterLesson(ctx, req.(*DeleteChapterLessonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ChapterLessonService_ServiceDesc is the grpc.ServiceDesc for ChapterLessonService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChapterLessonService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chapter_lesson.ChapterLessonService",
	HandlerType: (*ChapterLessonServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAllChapterLesson",
			Handler:    _ChapterLessonService_GetAllChapterLesson_Handler,
		},
		{
			MethodName: "CreateChapterLesson",
			Handler:    _ChapterLessonService_CreateChapterLesson_Handler,
		},
		{
			MethodName: "DetailChapterLesson",
			Handler:    _ChapterLessonService_DetailChapterLesson_Handler,
		},
		{
			MethodName: "EditChapterLesson",
			Handler:    _ChapterLessonService_EditChapterLesson_Handler,
		},
		{
			MethodName: "DeleteChapterLesson",
			Handler:    _ChapterLessonService_DeleteChapterLesson_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "chapter_lesson/chapter_lesson.proto",
}
