// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "watch_history/watch_history.proto" (package "watch_history", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { WatchHistoryService } from "./watch_history";
import type { EditLessonCompletionResponse } from "./watch_history";
import type { EditLessonCompletionRequest } from "./watch_history";
import type { EditWatchHistoryResponse } from "./watch_history";
import type { EditWatchHistoryRequest } from "./watch_history";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { WatchLessonIdResponse } from "./watch_history";
import type { WatchLessonIdRequest } from "./watch_history";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service watch_history.WatchHistoryService
 */
export interface IWatchHistoryServiceClient {
    /**
     * @generated from protobuf rpc: WatchLessonId
     */
    watchLessonId(input: WatchLessonIdRequest, options?: RpcOptions): UnaryCall<WatchLessonIdRequest, WatchLessonIdResponse>;
    /**
     * @generated from protobuf rpc: EditWatchHistory
     */
    editWatchHistory(input: EditWatchHistoryRequest, options?: RpcOptions): UnaryCall<EditWatchHistoryRequest, EditWatchHistoryResponse>;
    /**
     * rpc LastWatchHistory (LastWatchHistoryRequest) returns (LastWatchHistoryResponse);
     * rpc EditWatchHistory (EditWatchHistoryRequest) returns (EditWatchHistoryResponse);
     *
     * @generated from protobuf rpc: EditLessonCompletion
     */
    editLessonCompletion(input: EditLessonCompletionRequest, options?: RpcOptions): UnaryCall<EditLessonCompletionRequest, EditLessonCompletionResponse>;
}
/**
 * @generated from protobuf service watch_history.WatchHistoryService
 */
export class WatchHistoryServiceClient implements IWatchHistoryServiceClient, ServiceInfo {
    typeName = WatchHistoryService.typeName;
    methods = WatchHistoryService.methods;
    options = WatchHistoryService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: WatchLessonId
     */
    watchLessonId(input: WatchLessonIdRequest, options?: RpcOptions): UnaryCall<WatchLessonIdRequest, WatchLessonIdResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<WatchLessonIdRequest, WatchLessonIdResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: EditWatchHistory
     */
    editWatchHistory(input: EditWatchHistoryRequest, options?: RpcOptions): UnaryCall<EditWatchHistoryRequest, EditWatchHistoryResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<EditWatchHistoryRequest, EditWatchHistoryResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * rpc LastWatchHistory (LastWatchHistoryRequest) returns (LastWatchHistoryResponse);
     * rpc EditWatchHistory (EditWatchHistoryRequest) returns (EditWatchHistoryResponse);
     *
     * @generated from protobuf rpc: EditLessonCompletion
     */
    editLessonCompletion(input: EditLessonCompletionRequest, options?: RpcOptions): UnaryCall<EditLessonCompletionRequest, EditLessonCompletionResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<EditLessonCompletionRequest, EditLessonCompletionResponse>("unary", this._transport, method, opt, input);
    }
}
