// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "watch_history/watch_history.proto" (package "watch_history", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { WatchHistoryService } from "./watch_history";
import type { EditWatchHistoryResponse } from "./watch_history";
import type { EditWatchHistoryRequest } from "./watch_history";
import type { LastWatchHistoryResponse } from "./watch_history";
import type { LastWatchHistoryRequest } from "./watch_history";
import type { CreateWatchHistoryResponse } from "./watch_history";
import type { CreateWatchHistoryRequest } from "./watch_history";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { WatchLessonIdResponse } from "./watch_history";
import type { WatchLessonIdRequest } from "./watch_history";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service watch_history.WatchHistoryService
 */
export interface IWatchHistoryServiceClient {
    /**
     * @generated from protobuf rpc: WatchLessonId
     */
    watchLessonId(input: WatchLessonIdRequest, options?: RpcOptions): UnaryCall<WatchLessonIdRequest, WatchLessonIdResponse>;
    /**
     * @generated from protobuf rpc: CreateWatchHistory
     */
    createWatchHistory(input: CreateWatchHistoryRequest, options?: RpcOptions): UnaryCall<CreateWatchHistoryRequest, CreateWatchHistoryResponse>;
    /**
     * @generated from protobuf rpc: LastWatchHistory
     */
    lastWatchHistory(input: LastWatchHistoryRequest, options?: RpcOptions): UnaryCall<LastWatchHistoryRequest, LastWatchHistoryResponse>;
    /**
     * @generated from protobuf rpc: EditWatchHistory
     */
    editWatchHistory(input: EditWatchHistoryRequest, options?: RpcOptions): UnaryCall<EditWatchHistoryRequest, EditWatchHistoryResponse>;
}
/**
 * @generated from protobuf service watch_history.WatchHistoryService
 */
export class WatchHistoryServiceClient implements IWatchHistoryServiceClient, ServiceInfo {
    typeName = WatchHistoryService.typeName;
    methods = WatchHistoryService.methods;
    options = WatchHistoryService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: WatchLessonId
     */
    watchLessonId(input: WatchLessonIdRequest, options?: RpcOptions): UnaryCall<WatchLessonIdRequest, WatchLessonIdResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<WatchLessonIdRequest, WatchLessonIdResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: CreateWatchHistory
     */
    createWatchHistory(input: CreateWatchHistoryRequest, options?: RpcOptions): UnaryCall<CreateWatchHistoryRequest, CreateWatchHistoryResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<CreateWatchHistoryRequest, CreateWatchHistoryResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: LastWatchHistory
     */
    lastWatchHistory(input: LastWatchHistoryRequest, options?: RpcOptions): UnaryCall<LastWatchHistoryRequest, LastWatchHistoryResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<LastWatchHistoryRequest, LastWatchHistoryResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: EditWatchHistory
     */
    editWatchHistory(input: EditWatchHistoryRequest, options?: RpcOptions): UnaryCall<EditWatchHistoryRequest, EditWatchHistoryResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<EditWatchHistoryRequest, EditWatchHistoryResponse>("unary", this._transport, method, opt, input);
    }
}
