// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "watch_history/watch_history.proto" (package "watch_history", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { BaseResponse } from "../common/base_response";
import { FieldMask } from "../google/protobuf/field_mask";
/**
 * @generated from protobuf message watch_history.WatchLessonIdRequest
 */
export interface WatchLessonIdRequest {
    /**
     * @generated from protobuf field: string course_id = 1
     */
    courseId: string;
    /**
     * @generated from protobuf field: google.protobuf.FieldMask field_mask = 2
     */
    fieldMask?: FieldMask;
}
/**
 * @generated from protobuf message watch_history.WatchLessonIdResponse
 */
export interface WatchLessonIdResponse {
    /**
     * @generated from protobuf field: common.BaseResponse base = 1
     */
    base?: BaseResponse;
    /**
     * @generated from protobuf field: repeated watch_history.WatchHistoryInfo watched_lesson_id = 2
     */
    watchedLessonId: WatchHistoryInfo[]; // 'repeated' untuk array/slice
    /**
     * @generated from protobuf field: repeated watch_history.WatchHistoryInfo last_watch_history = 3
     */
    lastWatchHistory: WatchHistoryInfo[];
    /**
     * @generated from protobuf field: int32 lesson_count = 4
     */
    lessonCount: number;
}
/**
 * @generated from protobuf message watch_history.WatchHistoryInfo
 */
export interface WatchHistoryInfo {
    /**
     * @generated from protobuf field: string id = 1
     */
    id: string;
    /**
     * @generated from protobuf field: optional string user_id = 2
     */
    userId?: string;
    /**
     * @generated from protobuf field: optional string course_id = 3
     */
    courseId?: string;
    /**
     * @generated from protobuf field: optional string chapter_id = 4
     */
    chapterId?: string;
    /**
     * @generated from protobuf field: optional string lesson_id = 5
     */
    lessonId?: string;
    /**
     * @generated from protobuf field: optional string is_completed = 6
     */
    isCompleted?: string;
    /**
     * @generated from protobuf field: optional string created_at = 7
     */
    createdAt?: string;
    /**
     * @generated from protobuf field: optional string created_by = 8
     */
    createdBy?: string;
    /**
     * @generated from protobuf field: optional string deleted_by = 9
     */
    deletedBy?: string;
    /**
     * @generated from protobuf field: optional string updated_at = 10
     */
    updatedAt?: string;
    /**
     * @generated from protobuf field: optional string updated_by = 11
     */
    updatedBy?: string;
    /**
     * @generated from protobuf field: optional string deleted_at = 12
     */
    deletedAt?: string;
}
/**
 * @generated from protobuf message watch_history.CreateWatchHistoryRequest
 */
export interface CreateWatchHistoryRequest {
    /**
     * @generated from protobuf field: string id = 1
     */
    id: string;
    /**
     * @generated from protobuf field: string user_id = 2
     */
    userId: string;
    /**
     * @generated from protobuf field: string course_id = 3
     */
    courseId: string;
    /**
     * @generated from protobuf field: string chapter_id = 4
     */
    chapterId: string;
    /**
     * @generated from protobuf field: string lesson_id = 5
     */
    lessonId: string;
    /**
     * @generated from protobuf field: bool is_completed = 6
     */
    isCompleted: boolean;
}
/**
 * @generated from protobuf message watch_history.CreateWatchHistoryResponse
 */
export interface CreateWatchHistoryResponse {
    /**
     * @generated from protobuf field: common.BaseResponse base = 1
     */
    base?: BaseResponse;
    /**
     * @generated from protobuf field: string id = 2
     */
    id: string;
}
/**
 * @generated from protobuf message watch_history.LastWatchHistoryRequest
 */
export interface LastWatchHistoryRequest {
    /**
     * @generated from protobuf field: string user_id = 1
     */
    userId: string;
    /**
     * @generated from protobuf field: string course_id = 2
     */
    courseId: string;
    /**
     * @generated from protobuf field: google.protobuf.FieldMask field_mask = 3
     */
    fieldMask?: FieldMask;
}
/**
 * @generated from protobuf message watch_history.LastWatchHistoryResponse
 */
export interface LastWatchHistoryResponse {
    /**
     * @generated from protobuf field: common.BaseResponse base = 1
     */
    base?: BaseResponse;
    /**
     * @generated from protobuf field: repeated watch_history.WatchHistoryInfo history = 2
     */
    history: WatchHistoryInfo[];
}
/**
 * @generated from protobuf message watch_history.EditWatchHistoryRequest
 */
export interface EditWatchHistoryRequest {
    /**
     * @generated from protobuf field: string user_id = 1
     */
    userId: string;
    /**
     * @generated from protobuf field: string lesson_id = 2
     */
    lessonId: string;
}
/**
 * @generated from protobuf message watch_history.EditWatchHistoryResponse
 */
export interface EditWatchHistoryResponse {
    /**
     * @generated from protobuf field: common.BaseResponse base = 1
     */
    base?: BaseResponse;
    /**
     * @generated from protobuf field: string id = 2
     */
    id: string;
}
// @generated message type with reflection information, may provide speed optimized methods
class WatchLessonIdRequest$Type extends MessageType<WatchLessonIdRequest> {
    constructor() {
        super("watch_history.WatchLessonIdRequest", [
            { no: 1, name: "course_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "field_mask", kind: "message", T: () => FieldMask }
        ]);
    }
    create(value?: PartialMessage<WatchLessonIdRequest>): WatchLessonIdRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.courseId = "";
        if (value !== undefined)
            reflectionMergePartial<WatchLessonIdRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: WatchLessonIdRequest): WatchLessonIdRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string course_id */ 1:
                    message.courseId = reader.string();
                    break;
                case /* google.protobuf.FieldMask field_mask */ 2:
                    message.fieldMask = FieldMask.internalBinaryRead(reader, reader.uint32(), options, message.fieldMask);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: WatchLessonIdRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string course_id = 1; */
        if (message.courseId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.courseId);
        /* google.protobuf.FieldMask field_mask = 2; */
        if (message.fieldMask)
            FieldMask.internalBinaryWrite(message.fieldMask, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message watch_history.WatchLessonIdRequest
 */
export const WatchLessonIdRequest = new WatchLessonIdRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class WatchLessonIdResponse$Type extends MessageType<WatchLessonIdResponse> {
    constructor() {
        super("watch_history.WatchLessonIdResponse", [
            { no: 1, name: "base", kind: "message", T: () => BaseResponse },
            { no: 2, name: "watched_lesson_id", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => WatchHistoryInfo },
            { no: 3, name: "last_watch_history", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => WatchHistoryInfo },
            { no: 4, name: "lesson_count", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<WatchLessonIdResponse>): WatchLessonIdResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.watchedLessonId = [];
        message.lastWatchHistory = [];
        message.lessonCount = 0;
        if (value !== undefined)
            reflectionMergePartial<WatchLessonIdResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: WatchLessonIdResponse): WatchLessonIdResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* common.BaseResponse base */ 1:
                    message.base = BaseResponse.internalBinaryRead(reader, reader.uint32(), options, message.base);
                    break;
                case /* repeated watch_history.WatchHistoryInfo watched_lesson_id */ 2:
                    message.watchedLessonId.push(WatchHistoryInfo.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* repeated watch_history.WatchHistoryInfo last_watch_history */ 3:
                    message.lastWatchHistory.push(WatchHistoryInfo.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* int32 lesson_count */ 4:
                    message.lessonCount = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: WatchLessonIdResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* common.BaseResponse base = 1; */
        if (message.base)
            BaseResponse.internalBinaryWrite(message.base, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* repeated watch_history.WatchHistoryInfo watched_lesson_id = 2; */
        for (let i = 0; i < message.watchedLessonId.length; i++)
            WatchHistoryInfo.internalBinaryWrite(message.watchedLessonId[i], writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* repeated watch_history.WatchHistoryInfo last_watch_history = 3; */
        for (let i = 0; i < message.lastWatchHistory.length; i++)
            WatchHistoryInfo.internalBinaryWrite(message.lastWatchHistory[i], writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* int32 lesson_count = 4; */
        if (message.lessonCount !== 0)
            writer.tag(4, WireType.Varint).int32(message.lessonCount);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message watch_history.WatchLessonIdResponse
 */
export const WatchLessonIdResponse = new WatchLessonIdResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class WatchHistoryInfo$Type extends MessageType<WatchHistoryInfo> {
    constructor() {
        super("watch_history.WatchHistoryInfo", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "user_id", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "course_id", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "chapter_id", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "lesson_id", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "is_completed", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 7, name: "created_at", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 8, name: "created_by", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 9, name: "deleted_by", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 10, name: "updated_at", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 11, name: "updated_by", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 12, name: "deleted_at", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<WatchHistoryInfo>): WatchHistoryInfo {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        if (value !== undefined)
            reflectionMergePartial<WatchHistoryInfo>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: WatchHistoryInfo): WatchHistoryInfo {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                case /* optional string user_id */ 2:
                    message.userId = reader.string();
                    break;
                case /* optional string course_id */ 3:
                    message.courseId = reader.string();
                    break;
                case /* optional string chapter_id */ 4:
                    message.chapterId = reader.string();
                    break;
                case /* optional string lesson_id */ 5:
                    message.lessonId = reader.string();
                    break;
                case /* optional string is_completed */ 6:
                    message.isCompleted = reader.string();
                    break;
                case /* optional string created_at */ 7:
                    message.createdAt = reader.string();
                    break;
                case /* optional string created_by */ 8:
                    message.createdBy = reader.string();
                    break;
                case /* optional string deleted_by */ 9:
                    message.deletedBy = reader.string();
                    break;
                case /* optional string updated_at */ 10:
                    message.updatedAt = reader.string();
                    break;
                case /* optional string updated_by */ 11:
                    message.updatedBy = reader.string();
                    break;
                case /* optional string deleted_at */ 12:
                    message.deletedAt = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: WatchHistoryInfo, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        /* optional string user_id = 2; */
        if (message.userId !== undefined)
            writer.tag(2, WireType.LengthDelimited).string(message.userId);
        /* optional string course_id = 3; */
        if (message.courseId !== undefined)
            writer.tag(3, WireType.LengthDelimited).string(message.courseId);
        /* optional string chapter_id = 4; */
        if (message.chapterId !== undefined)
            writer.tag(4, WireType.LengthDelimited).string(message.chapterId);
        /* optional string lesson_id = 5; */
        if (message.lessonId !== undefined)
            writer.tag(5, WireType.LengthDelimited).string(message.lessonId);
        /* optional string is_completed = 6; */
        if (message.isCompleted !== undefined)
            writer.tag(6, WireType.LengthDelimited).string(message.isCompleted);
        /* optional string created_at = 7; */
        if (message.createdAt !== undefined)
            writer.tag(7, WireType.LengthDelimited).string(message.createdAt);
        /* optional string created_by = 8; */
        if (message.createdBy !== undefined)
            writer.tag(8, WireType.LengthDelimited).string(message.createdBy);
        /* optional string deleted_by = 9; */
        if (message.deletedBy !== undefined)
            writer.tag(9, WireType.LengthDelimited).string(message.deletedBy);
        /* optional string updated_at = 10; */
        if (message.updatedAt !== undefined)
            writer.tag(10, WireType.LengthDelimited).string(message.updatedAt);
        /* optional string updated_by = 11; */
        if (message.updatedBy !== undefined)
            writer.tag(11, WireType.LengthDelimited).string(message.updatedBy);
        /* optional string deleted_at = 12; */
        if (message.deletedAt !== undefined)
            writer.tag(12, WireType.LengthDelimited).string(message.deletedAt);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message watch_history.WatchHistoryInfo
 */
export const WatchHistoryInfo = new WatchHistoryInfo$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CreateWatchHistoryRequest$Type extends MessageType<CreateWatchHistoryRequest> {
    constructor() {
        super("watch_history.CreateWatchHistoryRequest", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/, options: { "buf.validate.field": { string: { minLen: "1", maxLen: "255" } } } },
            { no: 2, name: "user_id", kind: "scalar", T: 9 /*ScalarType.STRING*/, options: { "buf.validate.field": { string: { minLen: "1", maxLen: "255" } } } },
            { no: 3, name: "course_id", kind: "scalar", T: 9 /*ScalarType.STRING*/, options: { "buf.validate.field": { string: { minLen: "1", maxLen: "255" } } } },
            { no: 4, name: "chapter_id", kind: "scalar", T: 9 /*ScalarType.STRING*/, options: { "buf.validate.field": { string: { minLen: "1", maxLen: "255" } } } },
            { no: 5, name: "lesson_id", kind: "scalar", T: 9 /*ScalarType.STRING*/, options: { "buf.validate.field": { string: { minLen: "1", maxLen: "255" } } } },
            { no: 6, name: "is_completed", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<CreateWatchHistoryRequest>): CreateWatchHistoryRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        message.userId = "";
        message.courseId = "";
        message.chapterId = "";
        message.lessonId = "";
        message.isCompleted = false;
        if (value !== undefined)
            reflectionMergePartial<CreateWatchHistoryRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CreateWatchHistoryRequest): CreateWatchHistoryRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                case /* string user_id */ 2:
                    message.userId = reader.string();
                    break;
                case /* string course_id */ 3:
                    message.courseId = reader.string();
                    break;
                case /* string chapter_id */ 4:
                    message.chapterId = reader.string();
                    break;
                case /* string lesson_id */ 5:
                    message.lessonId = reader.string();
                    break;
                case /* bool is_completed */ 6:
                    message.isCompleted = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CreateWatchHistoryRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        /* string user_id = 2; */
        if (message.userId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.userId);
        /* string course_id = 3; */
        if (message.courseId !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.courseId);
        /* string chapter_id = 4; */
        if (message.chapterId !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.chapterId);
        /* string lesson_id = 5; */
        if (message.lessonId !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.lessonId);
        /* bool is_completed = 6; */
        if (message.isCompleted !== false)
            writer.tag(6, WireType.Varint).bool(message.isCompleted);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message watch_history.CreateWatchHistoryRequest
 */
export const CreateWatchHistoryRequest = new CreateWatchHistoryRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CreateWatchHistoryResponse$Type extends MessageType<CreateWatchHistoryResponse> {
    constructor() {
        super("watch_history.CreateWatchHistoryResponse", [
            { no: 1, name: "base", kind: "message", T: () => BaseResponse },
            { no: 2, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<CreateWatchHistoryResponse>): CreateWatchHistoryResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        if (value !== undefined)
            reflectionMergePartial<CreateWatchHistoryResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CreateWatchHistoryResponse): CreateWatchHistoryResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* common.BaseResponse base */ 1:
                    message.base = BaseResponse.internalBinaryRead(reader, reader.uint32(), options, message.base);
                    break;
                case /* string id */ 2:
                    message.id = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CreateWatchHistoryResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* common.BaseResponse base = 1; */
        if (message.base)
            BaseResponse.internalBinaryWrite(message.base, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* string id = 2; */
        if (message.id !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.id);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message watch_history.CreateWatchHistoryResponse
 */
export const CreateWatchHistoryResponse = new CreateWatchHistoryResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class LastWatchHistoryRequest$Type extends MessageType<LastWatchHistoryRequest> {
    constructor() {
        super("watch_history.LastWatchHistoryRequest", [
            { no: 1, name: "user_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "course_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "field_mask", kind: "message", T: () => FieldMask }
        ]);
    }
    create(value?: PartialMessage<LastWatchHistoryRequest>): LastWatchHistoryRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.userId = "";
        message.courseId = "";
        if (value !== undefined)
            reflectionMergePartial<LastWatchHistoryRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: LastWatchHistoryRequest): LastWatchHistoryRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string user_id */ 1:
                    message.userId = reader.string();
                    break;
                case /* string course_id */ 2:
                    message.courseId = reader.string();
                    break;
                case /* google.protobuf.FieldMask field_mask */ 3:
                    message.fieldMask = FieldMask.internalBinaryRead(reader, reader.uint32(), options, message.fieldMask);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: LastWatchHistoryRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string user_id = 1; */
        if (message.userId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.userId);
        /* string course_id = 2; */
        if (message.courseId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.courseId);
        /* google.protobuf.FieldMask field_mask = 3; */
        if (message.fieldMask)
            FieldMask.internalBinaryWrite(message.fieldMask, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message watch_history.LastWatchHistoryRequest
 */
export const LastWatchHistoryRequest = new LastWatchHistoryRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class LastWatchHistoryResponse$Type extends MessageType<LastWatchHistoryResponse> {
    constructor() {
        super("watch_history.LastWatchHistoryResponse", [
            { no: 1, name: "base", kind: "message", T: () => BaseResponse },
            { no: 2, name: "history", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => WatchHistoryInfo }
        ]);
    }
    create(value?: PartialMessage<LastWatchHistoryResponse>): LastWatchHistoryResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.history = [];
        if (value !== undefined)
            reflectionMergePartial<LastWatchHistoryResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: LastWatchHistoryResponse): LastWatchHistoryResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* common.BaseResponse base */ 1:
                    message.base = BaseResponse.internalBinaryRead(reader, reader.uint32(), options, message.base);
                    break;
                case /* repeated watch_history.WatchHistoryInfo history */ 2:
                    message.history.push(WatchHistoryInfo.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: LastWatchHistoryResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* common.BaseResponse base = 1; */
        if (message.base)
            BaseResponse.internalBinaryWrite(message.base, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* repeated watch_history.WatchHistoryInfo history = 2; */
        for (let i = 0; i < message.history.length; i++)
            WatchHistoryInfo.internalBinaryWrite(message.history[i], writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message watch_history.LastWatchHistoryResponse
 */
export const LastWatchHistoryResponse = new LastWatchHistoryResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class EditWatchHistoryRequest$Type extends MessageType<EditWatchHistoryRequest> {
    constructor() {
        super("watch_history.EditWatchHistoryRequest", [
            { no: 1, name: "user_id", kind: "scalar", T: 9 /*ScalarType.STRING*/, options: { "buf.validate.field": { string: { minLen: "1", maxLen: "255" } } } },
            { no: 2, name: "lesson_id", kind: "scalar", T: 9 /*ScalarType.STRING*/, options: { "buf.validate.field": { string: { minLen: "1", maxLen: "255" } } } }
        ]);
    }
    create(value?: PartialMessage<EditWatchHistoryRequest>): EditWatchHistoryRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.userId = "";
        message.lessonId = "";
        if (value !== undefined)
            reflectionMergePartial<EditWatchHistoryRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: EditWatchHistoryRequest): EditWatchHistoryRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string user_id */ 1:
                    message.userId = reader.string();
                    break;
                case /* string lesson_id */ 2:
                    message.lessonId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: EditWatchHistoryRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string user_id = 1; */
        if (message.userId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.userId);
        /* string lesson_id = 2; */
        if (message.lessonId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.lessonId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message watch_history.EditWatchHistoryRequest
 */
export const EditWatchHistoryRequest = new EditWatchHistoryRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class EditWatchHistoryResponse$Type extends MessageType<EditWatchHistoryResponse> {
    constructor() {
        super("watch_history.EditWatchHistoryResponse", [
            { no: 1, name: "base", kind: "message", T: () => BaseResponse },
            { no: 2, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<EditWatchHistoryResponse>): EditWatchHistoryResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        if (value !== undefined)
            reflectionMergePartial<EditWatchHistoryResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: EditWatchHistoryResponse): EditWatchHistoryResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* common.BaseResponse base */ 1:
                    message.base = BaseResponse.internalBinaryRead(reader, reader.uint32(), options, message.base);
                    break;
                case /* string id */ 2:
                    message.id = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: EditWatchHistoryResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* common.BaseResponse base = 1; */
        if (message.base)
            BaseResponse.internalBinaryWrite(message.base, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* string id = 2; */
        if (message.id !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.id);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message watch_history.EditWatchHistoryResponse
 */
export const EditWatchHistoryResponse = new EditWatchHistoryResponse$Type();
/**
 * @generated ServiceType for protobuf service watch_history.WatchHistoryService
 */
export const WatchHistoryService = new ServiceType("watch_history.WatchHistoryService", [
    { name: "WatchLessonId", options: {}, I: WatchLessonIdRequest, O: WatchLessonIdResponse },
    { name: "CreateWatchHistory", options: {}, I: CreateWatchHistoryRequest, O: CreateWatchHistoryResponse },
    { name: "LastWatchHistory", options: {}, I: LastWatchHistoryRequest, O: LastWatchHistoryResponse },
    { name: "EditWatchHistory", options: {}, I: EditWatchHistoryRequest, O: EditWatchHistoryResponse }
]);
